
import { Character } from './types';

export const HIRAGANA: Character[] = [
  { char: 'あ', romaji: 'a', thai: 'อะ', type: 'hiragana' }, { char: 'い', romaji: 'i', thai: 'อิ', type: 'hiragana' }, { char: 'う', romaji: 'u', thai: 'อุ', type: 'hiragana' }, { char: 'え', romaji: 'e', thai: 'เอะ', type: 'hiragana' }, { char: 'お', romaji: 'o', thai: 'โอะ', type: 'hiragana' },
  { char: 'か', romaji: 'ka', thai: 'คะ', type: 'hiragana' }, { char: 'き', romaji: 'ki', thai: 'คิ', type: 'hiragana' }, { char: 'く', romaji: 'ku', thai: 'คุ', type: 'hiragana' }, { char: 'け', romaji: 'ke', thai: 'เคะ', type: 'hiragana' }, { char: 'こ', romaji: 'ko', thai: 'โคะ', type: 'hiragana' },
  { char: 'さ', romaji: 'sa', thai: 'สะ', type: 'hiragana' }, { char: 'し', romaji: 'shi', thai: 'ชิ', type: 'hiragana' }, { char: 'す', romaji: 'su', thai: 'สุ', type: 'hiragana' }, { char: 'せ', romaji: 'se', thai: 'เซะ', type: 'hiragana' }, { char: 'そ', romaji: 'so', thai: 'โสะ', type: 'hiragana' },
  { char: 'た', romaji: 'ta', thai: 'ตะ', type: 'hiragana' }, { char: 'ち', romaji: 'chi', thai: 'ฌิ', type: 'hiragana' }, { char: 'つ', romaji: 'tsu', thai: 'ทสึ', type: 'hiragana' }, { char: 'て', romaji: 'te', thai: 'เตะ', type: 'hiragana' }, { char: 'と', romaji: 'to', thai: 'โตะ', type: 'hiragana' },
  { char: 'な', romaji: 'na', thai: 'นะ', type: 'hiragana' }, { char: 'に', romaji: 'ni', thai: 'นิ', type: 'hiragana' }, { char: 'ぬ', romaji: 'nu', thai: 'นุ', type: 'hiragana' }, { char: 'ね', romaji: 'ne', thai: 'เนะ', type: 'hiragana' }, { char: 'の', romaji: 'no', thai: 'โนะ', type: 'hiragana' },
  { char: 'は', romaji: 'ha', thai: 'ฮะ', type: 'hiragana' }, { char: 'ひ', romaji: 'hi', thai: 'ฮิ', type: 'hiragana' }, { char: 'ふ', romaji: 'fu', thai: 'ฟุ', type: 'hiragana' }, { char: 'へ', romaji: 'he', thai: 'เฮะ', type: 'hiragana' }, { char: 'ほ', romaji: 'ho', thai: 'โฮะ', type: 'hiragana' },
  { char: 'ま', romaji: 'ma', thai: 'มะ', type: 'hiragana' }, { char: 'み', romaji: 'mi', thai: 'มิ', type: 'hiragana' }, { char: 'む', romaji: 'mu', thai: 'มุ', type: 'hiragana' }, { char: 'め', romaji: 'me', thai: 'เมะ', type: 'hiragana' }, { char: 'も', romaji: 'mo', thai: 'โมะ', type: 'hiragana' },
  { char: 'や', romaji: 'ya', thai: 'ยะ', type: 'hiragana' }, { char: 'ゆ', romaji: 'yu', thai: 'ยุ', type: 'hiragana' }, { char: 'よ', romaji: 'yo', thai: 'โยะ', type: 'hiragana' },
  { char: 'ら', romaji: 'ra', thai: 'ระ', type: 'hiragana' }, { char: 'り', romaji: 'ri', thai: 'ริ', type: 'hiragana' }, { char: 'る', romaji: 'ru', thai: 'รุ', type: 'hiragana' }, { char: 'れ', romaji: 're', thai: 'เระ', type: 'hiragana' }, { char: 'ろ', romaji: 'ro', thai: 'โระ', type: 'hiragana' },
  { char: 'わ', romaji: 'wa', thai: 'วะ', type: 'hiragana' }, { char: 'を', romaji: 'wo', thai: 'โวะ', type: 'hiragana' }, { char: 'ん', romaji: 'n', thai: 'อึน', type: 'hiragana' }
];

export const HIRAGANA_DAKUTEN: Character[] = [
  { char: 'が', romaji: 'ga', thai: 'กะ', type: 'hiragana', isDakuten: true }, { char: 'ぎ', romaji: 'gi', thai: 'กิ', type: 'hiragana', isDakuten: true }, { char: 'ぐ', romaji: 'gu', thai: 'กุ', type: 'hiragana', isDakuten: true }, { char: 'げ', romaji: 'ge', thai: 'เกะ', type: 'hiragana', isDakuten: true }, { char: 'ご', romaji: 'go', thai: 'โกะ', type: 'hiragana', isDakuten: true },
  { char: 'ざ', romaji: 'za', thai: 'ซะ', type: 'hiragana', isDakuten: true }, { char: 'じ', romaji: 'ji', thai: 'จิ', type: 'hiragana', isDakuten: true }, { char: 'ず', romaji: 'zu', thai: 'ซึ', type: 'hiragana', isDakuten: true }, { char: 'ぜ', romaji: 'ze', thai: 'เซะ', type: 'hiragana', isDakuten: true }, { char: 'ぞ', romaji: 'zo', thai: 'โซะ', type: 'hiragana', isDakuten: true },
  { char: 'だ', romaji: 'da', thai: 'ดะ', type: 'hiragana', isDakuten: true }, { char: 'ぢ', romaji: 'ji', thai: 'จิ', type: 'hiragana', isDakuten: true }, { char: 'づ', romaji: 'zu', thai: 'สึ', type: 'hiragana', isDakuten: true }, { char: 'で', romaji: 'de', thai: 'เดะ', type: 'hiragana', isDakuten: true }, { char: 'ど', romaji: 'do', thai: 'โดะ', type: 'hiragana', isDakuten: true },
  { char: 'ば', romaji: 'ba', thai: 'บะ', type: 'hiragana', isDakuten: true }, { char: 'び', romaji: 'bi', thai: 'บิ', type: 'hiragana', isDakuten: true }, { char: 'ぶ', romaji: 'bu', thai: 'บุ', type: 'hiragana', isDakuten: true }, { char: 'べ', romaji: 'be', thai: 'เบะ', type: 'hiragana', isDakuten: true }, { char: 'ぼ', romaji: 'bo', thai: 'โบะ', type: 'hiragana', isDakuten: true },
  { char: 'ぱ', romaji: 'pa', thai: 'ปะ', type: 'hiragana', isDakuten: true }, { char: 'ぴ', romaji: 'pi', thai: 'ปิ', type: 'hiragana', isDakuten: true }, { char: 'ぷ', romaji: 'pu', thai: 'ปุ', type: 'hiragana', isDakuten: true }, { char: 'ぺ', romaji: 'pe', thai: 'เปะ', type: 'hiragana', isDakuten: true }, { char: 'ぽ', romaji: 'po', thai: 'โปะ', type: 'hiragana', isDakuten: true }
];

export const KATAKANA: Character[] = [
  { char: 'ア', romaji: 'a', thai: 'อะ', type: 'katakana' }, { char: 'イ', romaji: 'i', thai: 'อิ', type: 'katakana' }, { char: 'ウ', romaji: 'u', thai: 'อุ', type: 'katakana' }, { char: 'エ', romaji: 'e', thai: 'เอะ', type: 'katakana' }, { char: 'オ', romaji: 'o', thai: 'โอะ', type: 'katakana' },
  { char: 'カ', romaji: 'ka', thai: 'คะ', type: 'katakana' }, { char: 'キ', romaji: 'ki', thai: 'คิ', type: 'katakana' }, { char: 'ク', romaji: 'ku', thai: 'คุ', type: 'katakana' }, { char: 'ケ', romaji: 'ke', thai: 'เคะ', type: 'katakana' }, { char: 'コ', romaji: 'ko', thai: 'โคะ', type: 'katakana' },
  { char: 'サ', romaji: 'sa', thai: 'สะ', type: 'katakana' }, { char: 'シ', romaji: 'shi', thai: 'ชิ', type: 'katakana' }, { char: 'ス', romaji: 'su', thai: 'สุ', type: 'katakana' }, { char: 'セ', romaji: 'se', thai: 'เซะ', type: 'katakana' }, { char: 'ソ', romaji: 'so', thai: 'โสะ', type: 'katakana' },
  { char: 'タ', romaji: 'ta', thai: 'ตะ', type: 'katakana' }, { char: 'チ', romaji: 'chi', thai: 'ฌิ', type: 'katakana' }, { char: 'ツ', romaji: 'tsu', thai: 'ทสึ', type: 'katakana' }, { char: 'テ', romaji: 'te', thai: 'เตะ', type: 'katakana' }, { char: 'ト', romaji: 'to', thai: 'โตะ', type: 'katakana' },
  { char: 'ナ', romaji: 'na', thai: 'นะ', type: 'katakana' }, { char: 'ニ', romaji: 'ni', thai: 'นิ', type: 'katakana' }, { char: 'ヌ', romaji: 'nu', thai: 'นุ', type: 'katakana' }, { char: 'ネ', romaji: 'ne', thai: 'เนะ', type: 'katakana' }, { char: 'ノ', romaji: 'no', thai: 'โนะ', type: 'katakana' },
  { char: 'ハ', romaji: 'ha', thai: 'ฮะ', type: 'katakana' }, { char: 'ヒ', romaji: 'hi', thai: 'ฮิ', type: 'katakana' }, { char: 'フ', romaji: 'fu', thai: 'ฟุ', type: 'katakana' }, { char: 'ヘ', romaji: 'he', thai: 'เฮะ', type: 'katakana' }, { char: 'ホ', romaji: 'ho', thai: 'โฮะ', type: 'katakana' },
  { char: 'マ', romaji: 'ma', thai: 'มะ', type: 'katakana' }, { char: 'ミ', romaji: 'mi', thai: 'มิ', type: 'katakana' }, { char: 'ム', romaji: 'mu', thai: 'มุ', type: 'katakana' }, { char: 'メ', romaji: 'me', thai: 'เมะ', type: 'katakana' }, { char: 'モ', romaji: 'mo', thai: 'โมะ', type: 'katakana' },
  { char: 'ヤ', romaji: 'ya', thai: 'ยะ', type: 'katakana' }, { char: 'ユ', romaji: 'yu', thai: 'ยุ', type: 'katakana' }, { char: 'ヨ', romaji: 'yo', thai: 'โยะ', type: 'katakana' },
  { char: 'ラ', romaji: 'ra', thai: 'ระ', type: 'katakana' }, { char: 'リ', romaji: 'ri', thai: 'ริ', type: 'katakana' }, { char: 'ル', romaji: 'ru', thai: 'รุ', type: 'katakana' }, { char: 'レ', romaji: 're', thai: 'เระ', type: 'katakana' }, { char: 'ロ', romaji: 'ro', thai: 'โระ', type: 'katakana' },
  { char: 'ワ', romaji: 'wa', thai: 'วะ', type: 'katakana' }, { char: 'ヲ', romaji: 'wo', thai: 'โวะ', type: 'katakana' }, { char: 'ン', romaji: 'n', thai: 'อึน', type: 'katakana' }
];

export const KATAKANA_DAKUTEN: Character[] = [
  { char: 'ガ', romaji: 'ga', thai: 'กะ', type: 'katakana', isDakuten: true }, { char: 'ギ', romaji: 'gi', thai: 'กิ', type: 'katakana', isDakuten: true }, { char: 'グ', romaji: 'gu', thai: 'กุ', type: 'katakana', isDakuten: true }, { char: 'ゲ', romaji: 'ge', thai: 'เกะ', type: 'katakana', isDakuten: true }, { char: 'ゴ', romaji: 'go', thai: 'โกะ', type: 'katakana', isDakuten: true },
  { char: 'ザ', romaji: 'za', thai: 'ซะ', type: 'katakana', isDakuten: true }, { char: 'ジ', romaji: 'ji', thai: 'จิ', type: 'katakana', isDakuten: true }, { char: 'ズ', romaji: 'zu', thai: 'ซึ', type: 'katakana', isDakuten: true }, { char: 'ぜ', romaji: 'ze', thai: 'เซะ', type: 'katakana', isDakuten: true }, { char: 'ゾ', romaji: 'zo', thai: 'โซะ', type: 'katakana', isDakuten: true },
  { char: 'ด', romaji: 'da', thai: 'ดะ', type: 'katakana', isDakuten: true }, { char: 'ヂ', romaji: 'ji', thai: 'จิ', type: 'katakana', isDakuten: true }, { char: 'ヅ', romaji: 'zu', thai: 'สึ', type: 'katakana', isDakuten: true }, { char: 'デ', romaji: 'de', thai: 'เดะ', type: 'katakana', isDakuten: true }, { char: 'ド', romaji: 'do', thai: 'โดะ', type: 'katakana', isDakuten: true },
  { char: 'バ', romaji: 'ba', thai: 'บะ', type: 'katakana', isDakuten: true }, { char: 'ビ', romaji: 'bi', thai: 'บิ', type: 'katakana', isDakuten: true }, { char: 'ブ', romaji: 'bu', thai: 'บุ', type: 'katakana', isDakuten: true }, { char: 'べ', romaji: 'be', thai: 'เบะ', type: 'katakana', isDakuten: true }, { char: 'ボ', romaji: 'bo', thai: 'โบะ', type: 'katakana', isDakuten: true },
  { char: 'パ', romaji: 'pa', thai: 'ปะ', type: 'katakana', isDakuten: true }, { char: 'ピ', romaji: 'pi', thai: 'ปิ', type: 'katakana', isDakuten: true }, { char: 'ぷ', romaji: 'pu', thai: 'ปุ', type: 'katakana', isDakuten: true }, { char: 'ペ', romaji: 'pe', thai: 'เปะ', type: 'katakana', isDakuten: true }, { char: 'ポ', romaji: 'po', thai: 'โปะ', type: 'katakana', isDakuten: true }
];
