
import { SentenceQuestion } from './types.ts';

export const SENTENCES_N5: SentenceQuestion[] = [
  // --- 1-50: พื้นฐานคำช่วย (Basic Particles: は, の, も, と, か) ---
  { sentenceWithBlank: "私[わたし] _____ 学生[がくせい]です。", correctAnswer: "は", thaiTranslation: "ฉันเป็นนักเรียน", distractors: ["が", "を", "に"] },
  { sentenceWithBlank: "これ _____ 本[ほん]です。", correctAnswer: "は", thaiTranslation: "นี่คือหนังสือ", distractors: ["の", "を", "も"] },
  { sentenceWithBlank: "田中[たなか]さん _____ 先生[せんせい]です。", correctAnswer: "も", thaiTranslation: "คุณทานากะก็เป็นอาจารย์เหมือนกัน", distractors: ["は", "ที่", "を"] },
  { sentenceWithBlank: "これ _____ 何[なに]ですか。", correctAnswer: "は", thaiTranslation: "นี่คืออะไร", distractors: ["を", "が", "に"] },
  { sentenceWithBlank: "私[わたし] _____ 名前[なまえ]は ケンです。", correctAnswer: "の", thaiTranslation: "ชื่อของฉันคือเคน", distractors: ["は", "を", "に"] },
  { sentenceWithBlank: "山田[やまだ]さん _____ どこですか。", correctAnswer: "は", thaiTranslation: "คุณยามะดะอยู่ที่ไหน", distractors: ["が", "を", "に"] },
  { sentenceWithBlank: "それ _____ 私[わたし]の 傘[かさ]です。", correctAnswer: "は", thaiTranslation: "นั่นคือร่มของฉัน", distractors: ["を", "が", "に"] },
  { sentenceWithBlank: "あなた _____ 国[くに]は どこですか。", correctAnswer: "の", thaiTranslation: "ประเทศของคุณคือที่ไหน", distractors: ["は", "を", "が"] },
  { sentenceWithBlank: "あの 人[ひと] _____ 誰[だれ]ですか。", correctAnswer: "は", thaiTranslation: "คนนั้นคือใคร", distractors: ["ที่", "を", "に"] },
  { sentenceWithBlank: "本[ほん] _____ ノートを 買[か]いました。", correctAnswer: "と", thaiTranslation: "ซื้อหนังสือและสมุดบันทึก", distractors: ["を", "が", "に"] },
  { sentenceWithBlank: "コーヒー _____ 紅茶[こうちゃ]を 飲[の]みますか。", correctAnswer: "か", thaiTranslation: "จะดื่มกาแฟหรือชานะครับ/คะ", distractors: ["と", "を", "が"] },
  { sentenceWithBlank: "お父[とう]さん _____ お母[かあ]さんは どこですか。", correctAnswer: "と", thaiTranslation: "คุณพ่อและคุณแม่อยู่ที่ไหน", distractors: ["を", "に", "は"] },
  { sentenceWithBlank: "机[つくえ] _____ 上[うえ]に 本[ほん]が あります。", correctAnswer: "の", thaiTranslation: "มีหนังสืออยู่บนโต๊ะ", distractors: ["は", "を", "ที่"] },
  { sentenceWithBlank: "箱[はこ] _____ 中[なか]に 何[なに]が ありますか。", correctAnswer: "の", thaiTranslation: "ในกล่องมีอะไรอยู่หรือ", distractors: ["は", "を", "が"] },
  { sentenceWithBlank: "私[わたし] _____ 部屋[へや]は 二階[にかい]です。", correctAnswer: "の", thaiTranslation: "ห้องของฉันอยู่ชั้นสอง", distractors: ["は", "ที่", "に"] },
  { sentenceWithBlank: "日本[にほん] _____ 車[くるま]は とても 有名[ゆうめい]です。", correctAnswer: "の", thaiTranslation: "รถของญี่ปุ่นมีชื่อเสียงมาก", distractors: ["を", "が", "は"] },
  { sentenceWithBlank: "明日[あした] _____ 天気[てんき]は 何[なん]ですか。", correctAnswer: "の", thaiTranslation: "สภาพอากาศของวันพรุ่งนี้คืออะไร", distractors: ["は", "を", "ที่"] },
  { sentenceWithBlank: "これ _____ あなたの 鍵[かぎ]ですか。", correctAnswer: "は", thaiTranslation: "นี่คือกุญแจของคุณใช่ไหม", distractors: ["ที่", "を", "に"] },
  { sentenceWithBlank: "ここ _____ 教室[きょうしつ]です。", correctAnswer: "は", thaiTranslation: "ที่นี่คือห้องเรียน", distractors: ["ที่", "を", "に"] },
  { sentenceWithBlank: "あの ビル _____ 病院[びょういん]です。", correctAnswer: "は", thaiTranslation: "ตึกนั้นคือโรงพยาบาล", distractors: ["ที่", "を", "に"] },
  { sentenceWithBlank: "友達[ともだち] _____ ケンさんは 親切[しんせつ]です。", correctAnswer: "の", thaiTranslation: "เคนที่เป็นเพื่อนของฉันเป็นคนใจดี", distractors: ["は", "を", "に"] },
  { sentenceWithBlank: "これ _____ いくらですか。", correctAnswer: "は", thaiTranslation: "นี่ราคาเท่าไหร่", distractors: ["を", "ที่", "に"] },
  { sentenceWithBlank: "私[わたし] _____ 弟[おとうと]は 大学生[だいがくせい]です。", correctAnswer: "の", thaiTranslation: "น้องชายของฉันเป็นนักศึกษามหาวิทยาลัย", distractors: ["は", "を", "が"] },
  { sentenceWithBlank: "田中[たなか]さん _____ 車[くるま]は どれですか。", correctAnswer: "の", thaiTranslation: "รถของคุณทานากะคือคันไหน", distractors: ["は", "を", "ที่"] },
  { sentenceWithBlank: "昨日[きのう] _____ 夜[よる]、雨[あめ]が 降[ふ]りました。", correctAnswer: "の", thaiTranslation: "เมื่อคืนนี้ฝนตก", distractors: ["は", "を", "ที่"] },

  // --- 51-100: สถานที่และการเคลื่อนที่ (Places & Motion: に, へ, で) ---
  { sentenceWithBlank: "学校[がっこう] _____ 行[い]きます。", correctAnswer: "へ", thaiTranslation: "ไปโรงเรียน", distractors: ["を", "が", "で"] },
  { sentenceWithBlank: "家[うち] _____ 帰[かえ]ります。", correctAnswer: "へ", thaiTranslation: "กลับบ้าน", distractors: ["を", "ที่", "で"] },
  { sentenceWithBlank: "日本[にほん] _____ 来[き]ました。", correctAnswer: "へ", thaiTranslation: "มาที่ญี่ปุ่น", distractors: ["を", "ที่", "で"] },
  { sentenceWithBlank: "どこ _____ も 行[い]きません。", correctAnswer: "へ", thaiTranslation: "ไม่ไปที่ไหนเลย", distractors: ["を", "ที่", "に"] },
  { sentenceWithBlank: "教室[きょうしつ] _____ 勉強[べんきょう]します。", correctAnswer: "で", thaiTranslation: "เรียนที่ห้องเรียน", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "レストラン _____ ご飯[はん]を 食[た]べます。", correctAnswer: "で", thaiTranslation: "กินข้าวที่ร้านอาหาร", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "駅[えき] _____ 友達[ともだち]に 会[あ]います。", correctAnswer: "で", thaiTranslation: "เจอเพื่อนที่สถานี", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "公園[こうえん] _____ 散歩[さんぽ]します。", correctAnswer: "を", thaiTranslation: "เดินเล่นที่สวนสาธารณะ", distractors: ["ที่", "ที่", "へ"] },
  { sentenceWithBlank: "海[うみ] _____ 泳[およ]ぎます。", correctAnswer: "で", thaiTranslation: "ว่ายน้ำที่ทะเล", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "デパート _____ 買[か]い物[もの]を しました。", correctAnswer: "で", thaiTranslation: "ซื้อของที่ห้างสรรพสินค้า", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "椅子[いす] _____ 座[すわ]ってください。", correctAnswer: "に", thaiTranslation: "กรุณานั่งลงบนเก้าอี้", distractors: ["を", "ที่", "へ"] },
  { sentenceWithBlank: "ノート _____ 名前[なまえ]を 書[か]きます。", correctAnswer: "に", thaiTranslation: "เขียนชื่อลงในสมุด", distractors: ["を", "ที่", "へ"] },
  { sentenceWithBlank: "タクシー _____ 乗[の]りました。", correctAnswer: "に", thaiTranslation: "ขึ้นรถแท็กซี่", distractors: ["を", "ที่", "へ"] },
  { sentenceWithBlank: "日本[にほん] _____ 住[す]んでいます。", correctAnswer: "に", thaiTranslation: "อาศัยอยู่ที่ญี่ปุ่น", distractors: ["ที่", "を", "へ"] },
  { sentenceWithBlank: "銀行[ぎんこう] _____ 行[い]きたいです。", correctAnswer: "へ", thaiTranslation: "อยากไปธนาคาร", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "スーパー _____ パンを 買[か]いました。", correctAnswer: "で", thaiTranslation: "ซื้อขนมปังที่ซูเปอร์มาร์เก็ต", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "図書館[としょかん] _____ 本[ほん]を 読[よ]みます。", correctAnswer: "で", thaiTranslation: "อ่านหนังสือที่ห้องสมุด", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "庭[にわ] _____ 花[はな]が あります。", correctAnswer: "に", thaiTranslation: "มีดอกไม้อยู่ในสวน", distractors: ["ที่", "を", "へ"] },
  { sentenceWithBlank: "箱[はこ] _____ 手紙[てがみ]を 入[い]れました。", correctAnswer: "に", thaiTranslation: "ใส่จดหมายลงในกล่อง", distractors: ["を", "ที่", "へ"] },
  { sentenceWithBlank: "海[うみ] _____ 行[い]きましょう。", correctAnswer: "へ", thaiTranslation: "ไปทะเลกันเถอะ", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "ここ _____ 座[すわ]っても いいですか。", correctAnswer: "に", thaiTranslation: "นั่งตรงนี้ได้ไหมครับ", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "トイレ _____ 行[い]っても いいですか。", correctAnswer: "へ", thaiTranslation: "ขอไปห้องน้ำได้ไหมครับ", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "郵便局[ゆうびんきょく] _____ どこですか。", correctAnswer: "は", thaiTranslation: "ที่ทำการไปรษณีย์อยู่ที่ไหน", distractors: ["ที่", "を", "ที่"] },
  { sentenceWithBlank: "コンビニ _____ 水[みず]を 買[か]いました。", correctAnswer: "で", thaiTranslation: "ซื้อน้ำที่ร้านสะดวกซื้อ", distractors: ["ที่", "へ", "を"] },
  { sentenceWithBlank: "病院[びょういん] _____ 先生[せんせい]に 会[あ]います。", correctAnswer: "で", thaiTranslation: "เจอคุณหมอที่โรงพยาบาล", distractors: ["ที่", "へ", "を"] },

  // --- 101-150: เวลาและวันที่ (Time & Dates: に, から, まで) ---
  { sentenceWithBlank: "朝[あさ] 六時[ろくじ] _____ 起[お]きます。", correctAnswer: "に", thaiTranslation: "ตื่นนอนตอน 6 โมงเช้า", distractors: ["を", "へ", "ที่"] },
  { sentenceWithBlank: "夜[よる] 十一時[じゅういちじ] _____ 寝[ね]ます。", correctAnswer: "に", thaiTranslation: "นอนตอน 5 ทุ่ม", distractors: ["を", "へ", "ที่"] },
  { sentenceWithBlank: "仕事[しごと]は 九時[くじ] _____ です。", correctAnswer: "から", thaiTranslation: "งานเริ่มตั้งแต่ 9 โมง", distractors: ["จนถึง", "ที่", "へ"] },
  { sentenceWithBlank: "五時[ごじ] _____ 働[はたら]きます。", correctAnswer: "まで", thaiTranslation: "ทำงานจนถึง 5 โมง", distractors: ["ตั้งแต่", "ที่", "へ"] },
  { sentenceWithBlank: "休み[やすみ]は 何時[なんじ] _____ ですか。", correctAnswer: "まで", thaiTranslation: "พักจนถึงกี่โมง", distractors: ["ตั้งแต่", "ที่", "へ"] },
  { sentenceWithBlank: "三時[さんじ] _____ 会議[かいぎ]が あります。", correctAnswer: "に", thaiTranslation: "มีการประชุมตอน 3 โมง", distractors: ["を", "へ", "ที่"] },
  { sentenceWithBlank: "昨日[きのう]は 九時[くじ] _____ 勉強[べんきょう]しました。", correctAnswer: "まで", thaiTranslation: "เมื่อวานเรียนจนถึง 3 โมง", distractors: ["ตั้งแต่", "ที่", "へ"] },
  { sentenceWithBlank: "テストは 何曜日[なんようび] _____ ですか。", correctAnswer: "に", thaiTranslation: "สอบวันไหน (เจาะจงวัน)", distractors: ["を", "へ", "ตั้งแต่"] },
  { sentenceWithBlank: "誕生日[たんじょうび]は 十月[じゅうがつ] _____ です。", correctAnswer: "は", thaiTranslation: "วันเกิดคือเดือนตุลาคม", distractors: ["ที่", "を", "ที่"] },
  { sentenceWithBlank: "映画[えいが]は 何時[なんじ] _____ 始[はじ]まりますか。", correctAnswer: "に", thaiTranslation: "หนังเริ่มกี่โมง", distractors: ["を", "へ", "ที่"] },
  { sentenceWithBlank: "一月[いちがつ] 一日[ついたち] _____ 休みです。", correctAnswer: "は", thaiTranslation: "วันที่ 1 มกราคมเป็นวันหยุด", distractors: ["ที่", "を", "ที่"] },
  { sentenceWithBlank: "毎朝[まいあさ] 何時[なんじ] _____ 起[お]きますか。", correctAnswer: "に", thaiTranslation: "ทุกเช้าตื่นนอนกี่โมง", distractors: ["を", "へ", "ที่"] },
  { sentenceWithBlank: "勉強[べんきょう]は 何時[なんじ] _____ 終わりますか。", correctAnswer: "に", thaiTranslation: "เรียนเสร็จกี่โมง", distractors: ["を", "へ", "ที่"] },
  { sentenceWithBlank: "昨日[きのう] 九時[くじ] _____ 十時[じゅうじ] まで テレビを 見[み]ました。", correctAnswer: "から", thaiTranslation: "เมื่อวานดูทีวีตั้งแต่ 9 โมงถึง 10 โมง", distractors: ["จนถึง", "ที่", "へ"] },
  { sentenceWithBlank: "パーティーは 何時[なんじ] _____ ですか。", correctAnswer: "から", thaiTranslation: "ปาร์ตี้เริ่มตั้งแต่กี่โมง", distractors: ["จนถึง", "ที่", "へ"] },
  { sentenceWithBlank: "昼休み[ひるやすみ]は 十二時[じゅうにじ] _____ 一時[いちじ] までです。", correctAnswer: "から", thaiTranslation: "พักเที่ยงตั้งแต่เที่ยงถึงบ่ายโมง", distractors: ["จนถึง", "ที่", "へ"] },
  { sentenceWithBlank: "明日[あした] 十時[じゅうじ] _____ 会[あ]いましょう。", correctAnswer: "に", thaiTranslation: "พรุ่งนี้เจอกันตอน 10 โมงนะ", distractors: ["を", "へ", "ที่"] },
  { sentenceWithBlank: "宿題[しゅくだい]は 月曜日[げつようび] _____ 出[だ]してください。", correctAnswer: "まで", thaiTranslation: "กรุณาส่งการบ้านภายในวันจันทร์", distractors: ["ตั้งแต่", "ที่", "へ"] },
  { sentenceWithBlank: "一週間[いっしゅうかん] _____ 一回[いっかい] 買い物[かいもの]に 行[い]きます。", correctAnswer: "に", thaiTranslation: "ในหนึ่งสัปดาห์ไปซื้อของ 1 ครั้ง", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "何時[なんじ] _____ 日本語[にほんご]を 勉強[べんきょう]しますか。", correctAnswer: "に", thaiTranslation: "เรียนภาษาญี่ปุ่นตอนกี่โมง", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "月曜日[げつようび] _____ 金曜日[きんようび] まで 働[はたら]きます。", correctAnswer: "から", thaiTranslation: "ทำงานตั้งแต่วันจันทร์ถึงวันศุกร์", distractors: ["จนถึง", "ที่", "へ"] },
  { sentenceWithBlank: "夏[なつ]休[やす]み _____ どこへ 行[い]きましたか。", correctAnswer: "は", thaiTranslation: "วันหยุดฤดูร้อนไปที่ไหนมาหรือครับ", distractors: ["ที่", "を", "ที่"] },
  { sentenceWithBlank: "晩[ばん]ご飯[はん]を 食[た]べた _____、勉強[べんきょう]します。", correctAnswer: "後[あと]で", thaiTranslation: "หลังจากกินข้าวเย็นแล้ว จะเรียนหนังสือครับ", distractors: ["前[まえ]に", "時[とき]", "から"] },
  { sentenceWithBlank: "寝[ね]る _____ 本[ほん]を 読[よ]みます。", correctAnswer: "前[まえ]に", thaiTranslation: "ก่อนนอนจะอ่านหนังสือ", distractors: ["後[あと]で", "時[とき]", "から"] },
  { sentenceWithBlank: "暇[ひま]な _____、映画[えいが]を 見[み]ます。", correctAnswer: "時[とき]", thaiTranslation: "เวลาว่างจะดูหนัง", distractors: ["前[まえ]に", "後[あと]で", "から"] },

  // --- 151-200: กรรมและการกระทำ (Objects & Actions: を, が) ---
  { sentenceWithBlank: "水[みず] _____ 飲[の]みます。", correctAnswer: "を", thaiTranslation: "ดื่มน้ำ", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "ご飯[はん] _____ 食[た]べます。", correctAnswer: "を", thaiTranslation: "กินข้าว", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "本[ほん] _____ 読[よ]みます。", correctAnswer: "を", thaiTranslation: "อ่านหนังสือ", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "手紙[てがみ] _____ 書[か]きます。", correctAnswer: "を", thaiTranslation: "เขียนจดหมาย", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "写真[しゃしん] _____ 撮[と]ります。", correctAnswer: "を", thaiTranslation: "ถ่ายรูป", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "日本語[にほんご] _____ 話[はな]します。", correctAnswer: "を", thaiTranslation: "พูดภาษาญี่ปุ่น", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "音楽[おんがく] _____ 聞[き]きます。", correctAnswer: "を", thaiTranslation: "ฟังเพลง", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "テレビ _____ 見[み]ます。", correctAnswer: "を", thaiTranslation: "ดูทีวี", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "靴[くつ] _____ 買[か]いました。", correctAnswer: "を", thaiTranslation: "ซื้อรองเท้า", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "窓[まど] _____ 開[あ]けてください。", correctAnswer: "を", thaiTranslation: "กรุณาเปิดหน้าต่าง", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "ドア _____ 閉[し]めてください。", correctAnswer: "を", thaiTranslation: "กรุณาปิดประตู", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "名前[なまえ] _____ 教[おし]えてください。", correctAnswer: "を", thaiTranslation: "กรุณาบอกชื่อ", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "お茶[ちゃ] _____ 飲[の]みましょう。", correctAnswer: "を", thaiTranslation: "ดื่มชากันเถอะ", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "リンゴ _____ 買[か]いたいです。", correctAnswer: "を", thaiTranslation: "อยากซื้อแอปเปิ้ล", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "荷物[にもつ] _____ 送[おく]ります。", correctAnswer: "を", thaiTranslation: "ส่งของ", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "電気[でんき] _____ 消[け]してください。", correctAnswer: "を", thaiTranslation: "กรุณาปิดไฟ", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "タバコ _____ 吸[す]わないでください。", correctAnswer: "を", thaiTranslation: "กรุณาอย่าสูบบุหรี่", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "部屋[へや] _____ 掃除[そうじ]しました。", correctAnswer: "を", thaiTranslation: "ทำความสะอาดห้องแล้ว", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "料理[りょうり] _____ 好[す]きですか。", correctAnswer: "が", thaiTranslation: "ชอบทำอาหารไหม", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "日本語[にほんご] _____ 分[わ]かりますか。", correctAnswer: "が", thaiTranslation: "เข้าใจภาษาญี่ปุ่นไหม", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "テニス _____ 上手[じょうず]です。", correctAnswer: "が", thaiTranslation: "เล่นเทนนิสเก่ง", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "お金[かね] _____ ありません。", correctAnswer: "が", thaiTranslation: "ไม่มีเงิน", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "お腹[なか] _____ 痛い[いたい]です。", correctAnswer: "が", thaiTranslation: "ปวดท้องครับ/ค่ะ", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "エアコン _____ つけてください。", correctAnswer: "を", thaiTranslation: "กรุณาเปิดแอร์ครับ", distractors: ["ที่", "ที่", "は"] },
  { sentenceWithBlank: "名前[なまえ] _____ 書[か]いてください。", correctAnswer: "を", thaiTranslation: "กรุณาเขียนชื่อครับ", distractors: ["ที่", "ที่", "は"] },

  // --- 201-250: คุณศัพท์และการเปรียบเทียบ (Adjectives & Comparison) ---
  { sentenceWithBlank: "今日[きょう]は _____ ですね。", correctAnswer: "暑[あつ]い", thaiTranslation: "วันนี้ร้อนจังเลยเนอะ", distractors: ["寒[さむ]い", "白[しろ]い", "丸[まる]い"] },
  { sentenceWithBlank: "この 花[はな]は _____ です。", correctAnswer: "綺麗[きれい]", thaiTranslation: "ดอกไม้นี้สวย", distractors: ["静か[しずか]", "有名[ゆうめい]", "暑い[อทสึ่ย]"] },
  { sentenceWithBlank: "日本語[にほんご]は _____ ですか。", correctAnswer: "難[むずか]しい", thaiTranslation: "ภาษาญี่ปุ่นยากไหม", distractors: ["甘[あま]い", "赤[อะกะอิ]", "高[たか]い"] },
  { sentenceWithBlank: "あの 人[ひと]は _____ です。", correctAnswer: "親切[しันせつ]", thaiTranslation: "คนนั้นใจดี", distractors: ["暇[ฮิมะ]", "暗[คุระอิ]", "辛[คะระอิ]"] },
  { sentenceWithBlank: "この 料理[りょうり]は _____ です。", correctAnswer: "おいしい", thaiTranslation: "อาหารจานนี้อร่อย", distractors: ["狭[เซะมะอิ]", "寒[ซามุอิ]", "青[อะโอะอิ]"] },
  { sentenceWithBlank: "私[わたし]の 部屋[へや]は _____ です。", correctAnswer: "狭[せま]い", thaiTranslation: "ห้องของฉันแคบ", distractors: ["広[ฮิโระอิ]", "明[อะกะรุอิ]", "静[ชิซุกะ]"] },
  { sentenceWithBlank: "冬[ふゆ]は とても _____ です。", correctAnswer: "寒[さむ]い", thaiTranslation: "ฤดูหนาวหนาวมาก", distractors: ["暑[อทสึ่ย]", "広[ฮิโระอิ]", "綺麗[คิเร]"] },
  { sentenceWithBlank: "テストは _____ でした。", correctAnswer: "簡単[かんたん]", thaiTranslation: "ข้อสอบง่าย", distractors: ["賑[นิกิยากะ]", "親切[ชินเซ็ทสึ]", "静[ชิซุกะ]"] },
  { sentenceWithBlank: "あの 映画[えいが]は _____ です。", correctAnswer: "有名[ゆうめい]", thaiTranslation: "หนังเรื่องนั้นมีชื่อเสียง", distractors: ["親切[ชินเซ็ทสึ]", "暇[ฮิมะ]", "綺麗[คิเร]"] },
  { sentenceWithBlank: "田中[たなか]さんは _____ です。", correctAnswer: "元気[げんき]", thaiTranslation: "คุณทานากะแข็งแรงดี", distractors: ["静[ชิซุกะ]", "賑[นิกิยากะ]", "親切[ชินเซ็ทสึ]"] },
  { sentenceWithBlank: "今日[きょう]は _____ です。", correctAnswer: "暇[ひま]", thaiTranslation: "วันนี้ว่าง", distractors: ["賑[นิกิยากะ]", "有名[ยูเม]", "暑[อทสึ่ย]"] },
  { sentenceWithBlank: "テニス _____ サッカーの 方[ほう]が 好[す]きです。", correctAnswer: "より", thaiTranslation: "ชอบฟุตบอลมากกว่าเทนนิส", distractors: ["ほど", "と", "は"] },
  { sentenceWithBlank: "日本[にほん] _____ タイの 方[ほう]が 暑[あつ]いです。", correctAnswer: "より", thaiTranslation: "ประเทศไทยร้อนกว่าญี่ปุ่น", distractors: ["ほど", "と", "は"] },
  { sentenceWithBlank: "スポーツの 中[なか]で 何[なに] _____ 一番[いちばん] 好き[すき]ですか。", correctAnswer: "が", thaiTranslation: "ในบรรดากีฬา ชอบอะไรที่สุด", distractors: ["を", "は", "ที่"] },
  { sentenceWithBlank: "一年[いちねน]で いつ _____ 一番[いちばん] 寒[さむ]いですか。", correctAnswer: "が", thaiTranslation: "ในรอบปี ช่วงไหนหนาวที่สุด", distractors: ["を", "は", "ที่"] },
  { sentenceWithBlank: "リンゴ _____ バナナと どちらが 好[す]きですか。", correctAnswer: "と", thaiTranslation: "ระหว่างแอปเปิ้ลกับกล้วย ชอบอันไหนมากกว่า", distractors: ["より", "は", "ที่"] },
  { sentenceWithBlank: "この 部屋[へや]は あまり _____。", correctAnswer: "広[ひろ]くないです", thaiTranslation: "ห้องนี้ไม่ค่อยกว้าง", distractors: ["広[ฮิโระอิ]です", "広[ฮิโระอิ]でした", "広[ฮิโระอิ]かったです"] },
  { sentenceWithBlank: "昨日[きのう]の テストは _____。", correctAnswer: "難[むずか]しかったです", thaiTranslation: "ข้อสอบเมื่อวานยากครับ", distractors: ["難[มุซุกะชิ]いです", "難[มุซุกะชิ]くないです", "難[มุซุกะชิ]くなかったです"] },
  { sentenceWithBlank: "日本[にほん]の 料理[りょうり]は _____ です。", correctAnswer: "おいしい", thaiTranslation: "อาหารญี่ปุ่นอร่อย", distractors: ["甘[อะมะอิ]", "辛[คะระอิ]", "白[ชิโระอิ]"] },
  { sentenceWithBlank: "あの 人[ひと]は _____ 人[ひと] ですか。", correctAnswer: "どんな", thaiTranslation: "คนนั้นเป็นคนอย่างไร", distractors: ["どこ", "だれ", "いつ"] },
  { sentenceWithBlank: "背[せ] _____ 高い[たかい]です。", correctAnswer: "が", thaiTranslation: "ตัวสูง", distractors: ["を", "ที่", "は"] },
  { sentenceWithBlank: "目[め] _____ 赤い[あかい]です。", correctAnswer: "が", thaiTranslation: "ตาสีแดง", distractors: ["を", "ที่", "は"] },
  { sentenceWithBlank: "この パソコンは _____ です。", correctAnswer: "新[あたら]しい", thaiTranslation: "คอมพิวเตอร์เครื่องนี้ใหม่", distractors: ["古[ฟุรุอิ]", "丸[มารุอิ]", "白[ชิโระอิ]"] },
  { sentenceWithBlank: "私[わたし]は 日本[にほん]の 映画[えいが] _____ 好き[すき]です。", correctAnswer: "が", thaiTranslation: "ฉันชอบหนังญี่ปุ่น", distractors: ["を", "ที่", "は"] },
  { sentenceWithBlank: "弟[おとうと]は 字[じ] _____ 下手[へた]です。", correctAnswer: "が", thaiTranslation: "น้องชายเขียนตัวหนังสือไม่สวย (ไม่เก่ง)", distractors: ["を", "ที่", "は"] },

  // --- 251-300: การนับและเบ็ดเตล็ด (Counters & Mixed N5) ---
  { sentenceWithBlank: "リンゴを 五[いつ]つ _____。", correctAnswer: "買[か]いました", thaiTranslation: "ซื้อแอปเปิ้ล 5 ลูก", distractors: ["食[た]べました", "見[み]ました", "飲[の]みました"] },
  { sentenceWithBlank: "学生[がくせい]が 三人[さんにん] _____。", correctAnswer: "います", thaiTranslation: "มีนักเรียนอยู่ 3 คน", distractors: ["あります", "します", "きます"] },
  { sentenceWithBlank: "ビールを 二本[にほん] _____。", correctAnswer: "飲[の]みました", thaiTranslation: "ดื่มเบียร์ 2 ขวด", distractors: ["買[か]いました", "食[た]べました", "見[มิ]ました"] },
  { sentenceWithBlank: "猫[ねこ]が 一匹[いっぴき] _____。", correctAnswer: "います", thaiTranslation: "มีแมวอยู่ 1 ตัว", distractors: ["あります", "します", "きます"] },
  { sentenceWithBlank: "シャツを 二枚[にまい] _____。", correctAnswer: "買[か]いました", thaiTranslation: "ซื้อเสื้อเชิ้ต 2 ตัว", distractors: ["飲[โน]みました", "食[ตะ]べました", "見[มิ]ました"] },
  { sentenceWithBlank: "本[ほん]を 三冊[さんさつ] _____。", correctAnswer: "買[か]いました", thaiTranslation: "ซื้อหนังสือ 3 เล่ม", distractors: ["飲[โน]みました", "食[ตะ]べました", "見[มิ]ました"] },
  { sentenceWithBlank: "卵[たまご]を 十[とお] _____ 買[か]いました。", correctAnswer: "こ", thaiTranslation: "ซื้อไข่ 10 ฟอง", distractors: ["つ", "枚[ไม]", "本[ฮง]"] },
  { sentenceWithBlank: "全部[ぜんぶ] _____ いくらですか。", correctAnswer: "で", thaiTranslation: "ทั้งหมดราคาเท่าไหร่", distractors: ["ที่", "を", "は"] },
  { sentenceWithBlank: "コーヒーに 砂糖[さとう]を _____ ください。", correctAnswer: "入[い]れないで", thaiTranslation: "กรุณาอย่าใส่น้ำตาลในกาแฟ", distractors: ["入[เระ]て", "入[ฮิ]る", "入[เระ]た"] },
  { sentenceWithBlank: "ゆっくり _____ ください。", correctAnswer: "話[はな]して", thaiTranslation: "กรุณาพูดช้าๆ", distractors: ["話[ฮานา]す", "話[ฮานา]し", "話[ฮานา]した"] },
  { sentenceWithBlank: "もう一度[いちど] _____ ください。", correctAnswer: "言[い]って", thaiTranslation: "กรุณาพูดอีกครั้งหนึ่ง", distractors: ["言[อิ]う", "言[อิ]い", "言[อิ]った"] },
  { sentenceWithBlank: "ちょっと _____ ください。", correctAnswer: "待[ま]って", thaiTranslation: "กรุณารอสักครู่", distractors: ["行[อิ]って", "来[คิ]て", "見[มิ]て"] },
  { sentenceWithBlank: "傘[かさ]を _____ ください。", correctAnswer: "貸[か]して", thaiTranslation: "กรุณาให้ยืมร่มหน่อย", distractors: ["借[กะ]りて", "持[โมะ]って", "返[กะเอะ]して"] },
  { sentenceWithBlank: "テレビを _____ ながら ご飯[はん]を 食[た]べます。", correctAnswer: "見[み]", thaiTranslation: "กินข้าวไปพลางดูทีวีไปพลาง", distractors: ["見[มิ]て", "見[มิ]る", "見[มิ]た"] },
  { sentenceWithBlank: "日本語[にほんご]を _____ います。", correctAnswer: "勉強[べんきょう]して", thaiTranslation: "กำลังเรียนภาษาญี่ปุ่นอยู่", distractors: ["勉強[เบนเกียว]する", "勉強[เบนเกียว]し", "勉強[เบนเกียว]した"] },
  { sentenceWithBlank: "お父[とう]さんは 今[いま] テレビを _____ います。", correctAnswer: "見[み]て", thaiTranslation: "ตอนนี้คุณพ่อกำลังดูทีวีอยู่ครับ", distractors: ["見[มิ]る", "見[มิ]た", "見[มิ]に"] },
  { sentenceWithBlank: "鉛筆[えんぴつ] _____ 書[か]いてください。", correctAnswer: "で", thaiTranslation: "กรุณาเขียนด้วยดินสอ", distractors: ["ที่", "ที่", "ที่"] },
  { sentenceWithBlank: "会社[かいしゃ]まで 電車[でんしゃ] _____ 行[い]きます。", correctAnswer: "で", thaiTranslation: "ไปบริษัทโดยรถไฟ", distractors: ["ที่", "ที่", "ที่"] },
  { sentenceWithBlank: "自転車[じてんしゃ] _____ 行[い]きます。", correctAnswer: "で", thaiTranslation: "ไปโดยจักรยาน", distractors: ["ที่", "ที่", "ที่"] },
  { sentenceWithBlank: "昨日[きのう] パン _____ 卵[たまご]を 買[か]いました。", correctAnswer: "と", thaiTranslation: "เมื่อวานซื้อขนมปังกับไข่", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "お茶[ちゃ] _____ 飲[の]みませんか。", correctAnswer: "を", thaiTranslation: "ดื่มชาไหมครับ/คะ", distractors: ["ที่", "ที่", "ที่"] },
  { sentenceWithBlank: "一緒に[いっしょに] 公園[こうえん]へ _____。", correctAnswer: "行[い]きましょう", thaiTranslation: "ไปสวนสาธารณะด้วยกันเถอะ", distractors: ["行[อิ]きました", "行[อิ]きません", "行[อิ]きます"] },
  { sentenceWithBlank: "宿題[しゅくだい]は _____ ですか。", correctAnswer: "何[なに]", thaiTranslation: "การบ้านคืออะไร", distractors: ["どこ", "だれ", "いつ"] },
  { sentenceWithBlank: "この ペンを _____ も いいですか。", correctAnswer: "使[つか]って", thaiTranslation: "ขอใช้ปากกานี้ได้ไหมครับ", distractors: ["使[ทสึกะ]う", "使[ทสึกะ]い", "使[ทสึกะ]った"] },
  { sentenceWithBlank: "駅[えき]の 前[まえ] _____ 銀行[ぎんこう]が あります。", correctAnswer: "に", thaiTranslation: "ที่หน้าสถานีมีธนาคารอยู่", distractors: ["ที่", "は", "ที่"] },
  { sentenceWithBlank: "昨日[きのう]は どこへも _____。", correctAnswer: "行[い]きませんでした", thaiTranslation: "เมื่อวานไม่ได้ไปไหนเลย", distractors: ["行[อิ]きました", "行[อิ]きます", "行[อิ]きません"] },
  { sentenceWithBlank: "あした 三時[さんじ] _____ 会[あ]いましょう。", correctAnswer: "に", thaiTranslation: "พรุ่งนี้เจอกันตอน 3 โมงนะครับ", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "ここ _____ 荷物[にもつ]を 置[お]かないでください。", correctAnswer: "に", thaiTranslation: "กรุณาอย่าวางสิ่งของไว้ที่นี่", distractors: ["を", "ที่", "ที่"] },
  { sentenceWithBlank: "昨日[きのう] 十時[じゅうじ] _____ 寝[ね]ました。", correctAnswer: "に", thaiTranslation: "เมื่อวานนอนตอน 10 โมง (4 ทุ่ม)", distractors: ["ที่", "は", "ที่"] },
  { sentenceWithBlank: "毎日[まいにち] 漢字[かんじ]を _____ います。", correctAnswer: "練習[れんしゅう]して", thaiTranslation: "ฝึกเขียนคันจิอยู่ทุกวัน", distractors: ["練習[เรนชู]する", "練習[เรนชู]し", "練習[เรนชู]した"] }
];
