
import { Vocabulary } from './types';

export const VOCAB_N5: Vocabulary[] = [
  // สัตว์
  { word: 'ねこ', kanji: '猫', romaji: 'neko', thaiReading: 'เนะโกะ', meaning: 'แมว' },
  { word: 'いぬ', kanji: '犬', romaji: 'inu', thaiReading: 'อินุ', meaning: 'สุนัข' },
  { word: 'さかな', kanji: '魚', romaji: 'sakana', thaiReading: 'ซากานะ', meaning: 'ปลา' },
  { word: 'とり', kanji: '鳥', romaji: 'tori', thaiReading: 'โทริ', meaning: 'นก' },
  { word: 'うま', kanji: '馬', romaji: 'uma', thaiReading: 'อูมะ', meaning: 'ม้า' },
  { word: 'うし', kanji: '牛', romaji: 'ushi', thaiReading: 'อูชิ', meaning: 'วัว' },
  { word: 'ぶた', kanji: '豚', romaji: 'buta', thaiReading: 'บูตะ', meaning: 'หมู' },

  // ธรรมชาติและสภาพอากาศ
  { word: 'みず', kanji: '水', romaji: 'mizu', thaiReading: 'มิซุ', meaning: 'น้ำ' },
  { word: 'やま', kanji: '山', romaji: 'yama', thaiReading: 'ยามะ', meaning: 'ภูเขา' },
  { word: 'あめ', kanji: '雨', romaji: 'ame', thaiReading: 'อาเมะ', meaning: 'ฝน' },
  { word: 'はな', kanji: '花', romaji: 'hana', thaiReading: 'ฮานะ', meaning: 'ดอกไม้' },
  { word: 'うみ', kanji: '海', romaji: 'umi', thaiReading: 'อูมิ', meaning: 'ทะเล' },
  { word: 'そら', kanji: '空', romaji: 'sora', thaiReading: 'โซระ', meaning: 'ท้องฟ้า' },
  { word: 'かわ', kanji: '川', romaji: 'kawa', thaiReading: 'คาวะ', meaning: 'แม่น้ำ' },
  { word: 'ゆき', kanji: '雪', romaji: 'yuki', thaiReading: 'ยูกิ', meaning: 'หิมะ' },
  { word: 'かぜ', kanji: '風', romaji: 'kaze', thaiReading: 'คาเซะ', meaning: 'ลม' },
  { word: 'き', kanji: '木', romaji: 'ki', thaiReading: 'คิ', meaning: 'ต้นไม้' },

  // ครอบครัวและบุคคล
  { word: 'わたし', kanji: '私', romaji: 'watashi', thaiReading: 'วาตาชิ', meaning: 'ฉัน' },
  { word: 'あなた', kanji: '貴方', romaji: 'anata', thaiReading: 'อานาตะ', meaning: 'คุณ' },
  { word: 'せんせい', kanji: '先生', romaji: 'sensei', thaiReading: 'เซนเซ', meaning: 'คุณครู' },
  { word: 'ที่กุเซ', kanji: '学生', romaji: 'gakusei', thaiReading: 'กักเซ', meaning: 'นักเรียน' },
  { word: 'ちち', kanji: '父', romaji: 'chichi', thaiReading: 'ชิชิ', meaning: 'พ่อ (ของฉัน)' },
  { word: 'はは', kanji: '母', romaji: 'haha', thaiReading: 'ฮาฮะ', meaning: 'แม่ (ของฉัน)' },
  { word: 'おとうさん', kanji: 'お父さん', romaji: 'otousan', thaiReading: 'โอโตซัง', meaning: 'คุณพ่อ' },
  { word: 'おかあさん', kanji: 'お母さん', romaji: 'okaasan', thaiReading: 'โอกาซัง', meaning: 'คุณแม่' },
  { word: 'あに', kanji: '兄', romaji: 'ani', thaiReading: 'อานิ', meaning: 'พี่ชาย (ของฉัน)' },
  { word: 'あね', kanji: '姉', romaji: 'ane', thaiReading: 'อาเนะ', meaning: 'พี่สาว (ของฉัน)' },
  { word: 'おとうと', kanji: '弟', romaji: 'otouto', thaiReading: 'โอโตโตะ', meaning: 'น้องชาย' },
  { word: 'いもうと', kanji: '妹', romaji: 'imouto', thaiReading: 'อิโมโตะ', meaning: 'น้องสาว' },
  { word: 'ともだち', kanji: '友達', romaji: 'tomodachi', thaiReading: 'โทโมดาจิ', meaning: 'เพื่อน' },
  { word: 'ひと', kanji: '人', romaji: 'hito', thaiReading: 'ฮิโตะ', meaning: 'คน' },
  { word: 'こども', kanji: '子供', romaji: 'kodomo', thaiReading: 'โคโดโมะ', meaning: 'เด็ก' },

  // ร่างกาย
  { word: 'て', kanji: '手', romaji: 'te', thaiReading: 'เทะ', meaning: 'มือ' },
  { word: 'め', kanji: '目', romaji: 'me', thaiReading: 'เมะ', meaning: 'ตา' },
  { word: 'みみ', kanji: '耳', romaji: 'mimi', thaiReading: 'มิมิ', meaning: 'หู' },
  { word: 'くち', kanji: '口', romaji: 'kuchi', thaiReading: 'คุจิ', meaning: 'ปาก' },
  { word: 'あし', kanji: '足', romaji: 'ashi', thaiReading: 'อาชิ', meaning: 'ขา/เท้า' },
  { word: 'はな', kanji: '鼻', romaji: 'hana', thaiReading: 'ฮานะ', meaning: 'จมูก' },
  { word: 'あたま', kanji: '頭', romaji: 'อาตามะ', thaiReading: 'อาตามะ', meaning: 'หัว' },

  // อาหารและเครื่องดื่ม
  { word: 'たべもの', kanji: '食べ物', romaji: 'tabemono', thaiReading: 'ทาเบโมโนะ', meaning: 'ของกิน' },
  { word: 'のみもの', kanji: '飲み物', romaji: 'nomimono', thaiReading: 'โนมิโมโนะ', meaning: 'เครื่องดื่ม' },
  { word: 'ごはん', kanji: 'ご飯', romaji: 'gohan', thaiReading: 'โกฮัง', meaning: 'ข้าว' },
  { word: 'おちゃ', kanji: 'お茶', romaji: 'ocha', thaiReading: 'โอจะ', meaning: 'ชา' },
  { word: 'ぎゅうにゅう', kanji: '牛乳', romaji: 'gyuunyuu', thaiReading: 'กิว นิว', meaning: 'นมวัว' },
  { word: 'たまご', kanji: '卵', romaji: 'tamago', thaiReading: 'ทามาโกะ', meaning: 'ไข่' },
  { word: 'にく', kanji: '肉', romaji: 'niku', thaiReading: 'นิกุ', meaning: 'เนื้อ' },
  { word: 'やさい', kanji: '野菜', romaji: 'yasai', thaiReading: 'ยาไซ', meaning: 'ผัก' },
  { word: 'くだもの', kanji: '果物', romaji: 'kudamono', thaiReading: 'คุดาโมโนะ', meaning: 'ผลไม้' },
  { word: 'おさけ', kanji: 'お酒', romaji: 'osake', thaiReading: 'โอสาเกะ', meaning: 'เหล้า' },
  { word: 'パン', romaji: 'pan', thaiReading: 'ปัง', meaning: 'ขนมปัง' },

  // เวลา
  { word: 'いま', kanji: '今', romaji: 'ima', thaiReading: 'อิมา', meaning: 'ตอนนี้' },
  { word: 'きょう', kanji: '今日', romaji: 'kyou', thaiReading: 'เคียว', meaning: 'วันนี้' },
  { word: 'あした', kanji: '明日', romaji: 'ashita', thaiReading: 'อาชิตะ', meaning: 'พรุ่งนี้' },
  { word: 'きのう', kanji: '昨日', romaji: 'kinou', thaiReading: 'คิโน', meaning: 'เมื่อวาน' },
  { word: 'あさ', kanji: '朝', romaji: 'asa', thaiReading: 'อาสะ', meaning: 'ตอนเช้า' },
  { word: 'ひる', kanji: '昼', romaji: 'hiru', thaiReading: 'ฮิรุ', meaning: 'กลางวัน' },
  { word: 'ばん', kanji: '晩', romaji: 'ban', thaiReading: 'บัง', meaning: 'ตอนเย็น' },
  { word: 'よる', kanji: '夜', romaji: 'yoru', thaiReading: 'โยรุ', meaning: 'กลางคืน' },
  { word: 'まいあさ', kanji: '毎朝', romaji: 'maiasa', thaiReading: 'ไมอาสะ', meaning: 'ทุกเช้า' },
  { word: 'まいにち', kanji: '毎日', romaji: 'mainichi', thaiReading: 'ไมนิจิ', meaning: 'ทุกวัน' },
  { word: 'らいしゅう', kanji: '来週', romaji: 'raishuu', thaiReading: 'ไรชู', meaning: 'สัปดาห์หน้า' },
  { word: 'せんしゅう', kanji: '先週', romaji: 'senshuu', thaiReading: 'เซนชู', meaning: 'สัปดาห์ที่แล้ว' },
  { word: 'ことし', kanji: '今年', romaji: 'kotoshi', thaiReading: 'โคโตชิ', meaning: 'ปีนี้' },
  { word: 'きょねん', kanji: '去年', romaji: 'kyonen', thaiReading: 'เคียวเน็น', meaning: 'ปีที่แล้ว' },
  { word: 'らいねん', kanji: '来年', romaji: 'rainen', thaiReading: 'ไรเน็น', meaning: 'ปีหน้า' },

  // สถานที่และสิ่งของ
  { word: 'ほん', kanji: '本', romaji: 'hon', thaiReading: 'ฮง', meaning: 'หนังสือ' },
  { word: 'にほん', kanji: '日本', romaji: 'nihon', thaiReading: 'นิฮง', meaning: 'ญี่ปุ่น' },
  { word: 'とけい', kanji: '時計', romaji: 'tokei', thaiReading: 'โทเค', meaning: 'นาฬิกา' },
  { word: 'かばん', romaji: 'kaban', thaiReading: 'คาบัง', meaning: 'กระเป๋า' },
  { word: 'ぎんこう', kanji: '銀行', romaji: 'ginkou', thaiReading: 'กินโก', meaning: 'ธนาคาร' },
  { word: 'でんわ', kanji: '電話', romaji: 'denwa', thaiReading: 'เดนวะ', meaning: 'โทรศัพท์' },
  { word: 'くるま', kanji: '車', romaji: 'kuruma', thaiReading: 'คุรุมะ', meaning: 'รถยนต์' },
  { word: 'がっこう', kanji: '学校', romaji: 'gakkou', thaiReading: 'กักโก', meaning: 'โรงเรียน' },
  { word: 'えき', kanji: '駅', romaji: 'eki', thaiReading: 'เอกิ', meaning: 'สถานีรถไฟ' },
  { word: 'いえ', kanji: '家', romaji: 'ie', thaiReading: 'อิเอะ', meaning: 'บ้าน' },
  { word: 'へや', kanji: '部屋', romaji: 'heya', thaiReading: 'เฮยะ', meaning: 'ห้อง' },
  { word: 'つくえ', kanji: '机', romaji: 'tsukue', thaiReading: 'ทสึกุเอะ', meaning: 'โต๊ะ' },
  { word: 'いす', romaji: 'isu', thaiReading: 'อิซุ', meaning: 'เก้าอี้' },
  { word: 'しんぶん', kanji: '新聞', romaji: 'shinbun', thaiReading: 'ชิมบุง', meaning: 'หนังสือพิมพ์' },
  { word: 'じしょ', kanji: '辞書', romaji: 'jisho', thaiReading: 'จิโชะ', meaning: 'พจนานุกรม' },
  { word: 'じてんしゃ', kanji: '自転車', romaji: 'jitensha', thaiReading: 'จิเทนฉะ', meaning: 'จักรยาน' },
  { word: 'ちかてつ', kanji: '地下鉄', romaji: 'chikatetsu', thaiReading: 'จิกะเททสึ', meaning: 'รถไฟใต้ดิน' },
  { word: 'ひこうき', kanji: '飛行機', romaji: 'hikouki', thaiReading: 'ฮิโกกิ', meaning: 'เครื่องบิน' },
  { word: 'おてあらい', kanji: 'お手洗い', romaji: 'otearai', thaiReading: 'โอเทอาราย', meaning: 'ห้องน้ำ' },
  { word: 'きょうしつ', kanji: '教室', romaji: 'kyoushitsu', thaiReading: 'เคียวชิทสึ', meaning: 'ห้องเรียน' },

  // กริยา (Verbs)
  { word: 'たべる', kanji: '食べる', romaji: 'taberu', thaiReading: 'ทาเบรุ', meaning: 'กิน' },
  { word: 'のむ', kanji: '飲む', romaji: 'nomu', thaiReading: 'โนมุ', meaning: 'ดื่ม' },
  { word: 'いく', kanji: '行く', romaji: 'iku', thaiReading: 'อิกุ', meaning: 'ไป' },
  { word: 'くる', kanji: '来る', romaji: 'kuru', thaiReading: 'คุรุ', meaning: 'มา' },
  { word: 'かえる', kanji: '帰る', romaji: 'kaeru', thaiReading: 'คาเอรุ', meaning: 'กลับ' },
  { word: 'みる', kanji: '見る', romaji: 'miru', thaiReading: 'มิรุ', meaning: 'ดู/เห็น' },
  { word: 'きく', kanji: '聞く', romaji: 'kiku', thaiReading: 'คิกุ', meaning: 'ฟัง/ถาม' },
  { word: 'よむ', kanji: '読む', romaji: 'yomu', thaiReading: 'โยมุ', meaning: 'อ่าน' },
  { word: 'かく', kanji: '書く', romaji: 'kaku', thaiReading: 'คากุ', meaning: 'เขียน' },
  { word: 'かう', kanji: '買う', romaji: 'kau', thaiReading: 'คาอุ', meaning: 'ซื้อ' },
  { word: 'とる', kanji: '撮る', romaji: 'toru', thaiReading: 'โทรุ', meaning: 'ถ่ายรูป' },
  { word: 'する', romaji: 'suru', thaiReading: 'ซุรุ', meaning: 'ทำ' },
  { word: 'べんきょうする', kanji: '勉強する', romaji: 'benkyousuru', thaiReading: 'เบนเคียว ซุรุ', meaning: 'เรียน' },
  { word: 'ねる', kanji: '寝る', romaji: 'neru', thaiReading: 'เนรุ', meaning: 'นอน' },
  { word: 'おきる', kanji: '起きる', romaji: 'okiru', thaiReading: 'โอกิรุ', meaning: 'ตื่น' },
  { word: 'あう', kanji: '会う', romaji: 'au', thaiReading: 'อาอุ', meaning: 'พบ/เจอ' },
  { word: 'あそぶ', kanji: '遊ぶ', romaji: 'asobu', thaiReading: 'อาโซบุ', meaning: 'เล่น' },
  { word: 'まつ', kanji: '待つ', romaji: 'matsu', thaiReading: 'มัทสึ', meaning: 'รอ' },
  { word: 'はなす', kanji: '話す', romaji: 'hanasu', thaiReading: 'ฮานาสุ', meaning: 'พูด' },
  { word: 'いう', kanji: '言う', romaji: 'iu', thaiReading: 'อิอุ', meaning: 'พูด/กล่าว' },
  { word: 'ある', romaji: 'aru', thaiReading: 'อารุ', meaning: 'มี/อยู่ (สิ่งของ)' },
  { word: 'いる', romaji: 'iru', thaiReading: 'อิรุ', meaning: 'มี/อยู่ (คน สัตว์)' },

  // คุณศัพท์ (Adjectives)
  { word: 'いい', romaji: 'ii', thaiReading: 'อี้', meaning: 'ดี' },
  { word: 'わるい', kanji: '悪い', romaji: 'warui', thaiReading: 'วารุ่ย', meaning: 'เลว/ไม่ดี' },
  { word: 'おおきい', kanji: '大きい', romaji: 'ookii', thaiReading: 'โอกี้', meaning: 'ใหญ่' },
  { word: 'ちいさい', kanji: '小さい', romaji: 'chiisai', thaiReading: 'ชิไซ้', meaning: 'เล็ก' },
  { word: 'たかい', kanji: '高い', romaji: 'takai', thaiReading: 'ทาก้าย', meaning: 'สูง/แพง' },
  { word: 'やすい', kanji: '安い', romaji: 'yasui', thaiReading: 'ยาซุ่ย', meaning: 'ถูก' },
  { word: 'あつい', kanji: '暑い', romaji: 'atsui', thaiReading: 'อาทสึ่ย', meaning: 'ร้อน (อากาศ)' },
  { word: 'さむい', kanji: '寒い', romaji: 'samui', thaiReading: 'ซามุ่ย', meaning: 'หนาว (อากาศ)' },
  { word: 'おもしろい', romaji: 'omoshiroi', thaiReading: 'โอโมชิโร่ย', meaning: 'น่าสนใจ/สนุก' },
  { word: 'おいしい', romaji: 'oishii', thaiReading: 'โออิชี่', meaning: 'อร่อย' },
  { word: 'いそがしい', kanji: '忙しい', romaji: 'isogashii', thaiReading: 'อิโซกาชี่', meaning: 'ยุ่ง' },
  { word: 'あたらしい', kanji: '新しい', romaji: 'atarashii', thaiReading: 'อาตาราชี่', meaning: 'ใหม่' },
  { word: 'ふるい', kanji: '古い', romaji: 'furui', thaiReading: 'ฟุรุ่ย', meaning: 'เก่า' },
  { word: 'むずかしい', kanji: '難しい', romaji: 'muzukashii', thaiReading: 'มุซุกาชี่', meaning: 'ยาก' },
  { word: 'やさしい', romaji: 'yasashii', thaiReading: 'ยาซาชี่', meaning: 'ง่าย/ใจดี' },
  { word: 'ながい', kanji: '長い', romaji: 'nagai', thaiReading: 'นาก้าย', meaning: 'ยาว' },
  { word: 'みじかい', kanji: '短い', romaji: 'mijikai', thaiReading: 'มิจิก้าย', meaning: 'สั้น' },
  { word: 'ひろい', kanji: '広い', romaji: 'hiroi', thaiReading: 'ฮิโร่ย', meaning: 'กว้าง' },
  { word: 'せまい', kanji: '狭い', romaji: 'semai', thaiReading: 'เซไม่', meaning: 'แคบ' },

  // สี
  { word: 'あかい', kanji: '赤い', romaji: 'akai', thaiReading: 'อาก้าย', meaning: 'สีแดง' },
  { word: 'あおい', kanji: '青い', romaji: 'aoi', thaiReading: 'อาโอ่ย', meaning: 'สีน้ำเงิน' },
  { word: 'くろい', kanji: '黒い', romaji: 'kuroi', thaiReading: 'คุโร่ย', meaning: 'สีดำ' },
  { word: 'しろい', kanji: '白い', romaji: 'shiroi', thaiReading: 'ชิโร่ย', meaning: 'สีขาว' },
  { word: 'きいろい', kanji: '黄色い', romaji: 'kiiroi', thaiReading: 'คิอิโร่ย', meaning: 'สีเหลือง' },

  // อื่นๆ
  { word: 'とても', romaji: 'totemo', thaiReading: 'โทเทโมะ', meaning: 'มาก' },
  { word: 'すこし', kanji: '少し', romaji: 'sukoshi', thaiReading: 'สุโกชิ', meaning: 'นิดหน่อย' },
  { word: 'ぜんぜん', romaji: 'zenzen', thaiReading: 'เซนเซน', meaning: 'ไม่เลย' },
  { word: 'たくさん', romaji: 'takusan', thaiReading: 'ทากุซัง', meaning: 'จำนวนมาก' },
  { word: 'どこ', romaji: 'doko', thaiReading: 'โดโกะ', meaning: 'ที่ไหน' },
  { word: 'いつ', romaji: 'itsu', thaiReading: 'อิทสึ', meaning: 'เมื่อไหร่' },
  { word: 'なに', kanji: '何', romaji: 'nani', thaiReading: 'นานิ', meaning: 'อะไร' },
  { word: 'だれ', romaji: 'dare', thaiReading: 'ดาเระ', meaning: 'ใคร' },
  { word: 'どうして', romaji: 'doushite', thaiReading: 'โดชิเตะ', meaning: 'ทำไม' },

  // เพิ่มเติมกลุ่ม Verbs 2
  { word: 'うたう', kanji: '歌う', romaji: 'utau', thaiReading: 'อูตาอุ', meaning: 'ร้องเพลง' },
  { word: 'およぐ', kanji: '泳ぐ', romaji: 'oyogu', thaiReading: 'โอยอกุ', meaning: 'ว่ายน้ำ' },
  { word: 'だす', kanji: '出す', romaji: 'dasu', thaiReading: 'ดาสุ', meaning: 'เอาออก/ส่ง' },
  { word: 'たつ', kanji: '立つ', romaji: 'tatsu', thaiReading: 'ทัทสึ', meaning: 'ยืน' },
  { word: 'すわる', kanji: '座る', romaji: 'suwaru', thaiReading: 'ซุวารุ', meaning: 'นั่ง' },
  { word: 'つかう', kanji: '使う', romaji: 'tsukau', thaiReading: 'ทสึกาอุ', meaning: 'ใช้' },
  { word: 'つく', kanji: '着く', romaji: 'tsuku', thaiReading: 'ทสึคุ', meaning: 'ถึง (สถานที่)' },
  { word: 'つくる', kanji: '作る', romaji: 'tsukuru', thaiReading: 'ทสึกุรุ', meaning: 'ทำ/ผลิต' },
  { word: 'つける', romaji: 'tsukeru', thaiReading: 'ทสึเกรุ', meaning: 'เปิด (ไฟ)' },
  { word: 'けす', kanji: '消す', romaji: 'kesu', thaiReading: 'เคซุ', meaning: 'ปิด (ไฟ)/ลบ' },
  { word: 'あける', kanji: '開ける', romaji: 'akeru', thaiReading: 'อาเกรุ', meaning: 'เปิด (ประตู)' },
  { word: 'しめる', kanji: '閉める', romaji: 'shimeru', thaiReading: 'ชิเมรุ', meaning: 'ปิด (ประตู)' },

  // เพิ่มเติมกลุ่ม Adjectives (Na)
  { word: 'しずか', kanji: '静か', romaji: 'shizuka', thaiReading: 'ชิซุกะ', meaning: 'เงียบ' },
  { word: 'にぎやか', romaji: 'nigiyaka', thaiReading: 'นิกิยากะ', meaning: 'ครึกครื้น' },
  { word: 'きれい', romaji: 'kirei', thaiReading: 'คิเร', meaning: 'สวย/สะอาด' },
  { word: 'ひま', kanji: '暇', romaji: 'hima', thaiReading: 'ฮิมะ', meaning: 'ว่าง' },
  { word: 'べんり', kanji: '便利', romaji: 'benri', thaiReading: 'เบนริ', meaning: 'สะดวกสบาย' },
  { word: 'すき', kanji: '好き', romaji: 'suki', thaiReading: 'สุกิ', meaning: 'ชอบ' },
  { word: 'きらい', kanji: '嫌い', romaji: 'kirai', thaiReading: 'คิไร', meaning: 'เกลียด' },
  { word: 'じょうず', kanji: '上手', romaji: 'jouzu', thaiReading: 'โจซุ', meaning: 'เก่ง' },
  { word: 'へた', kanji: '下手', romaji: 'heta', thaiReading: 'เฮตะ', meaning: 'ไม่เก่ง' },

  // ตัวเลขเบื้องต้น
  { word: 'いち', kanji: '一', romaji: 'ichi', thaiReading: 'อิจิ', meaning: 'หนึ่ง' },
  { word: 'に', kanji: '二', romaji: 'ni', thaiReading: 'นิ', meaning: 'สอง' },
  { word: 'さん', kanji: '三', romaji: 'san', thaiReading: 'ซัง', meaning: 'สาม' },
  { word: 'よん', kanji: '四', romaji: 'yon', thaiReading: 'ยง', meaning: 'สี่' },
  { word: 'ご', kanji: '五', romaji: 'go', thaiReading: 'โกะ', meaning: 'ห้า' },
  { word: 'ろく', kanji: '六', romaji: 'roku', thaiReading: 'โรกุ', meaning: 'หก' },
  { word: 'なな', kanji: '七', romaji: 'nana', thaiReading: 'นานะ', meaning: 'เจ็ด' },
  { word: 'はち', kanji: '八', romaji: 'hachi', thaiReading: 'ฮาจิ', meaning: 'แปด' },
  { word: 'きゅう', kanji: '九', romaji: 'kyuu', thaiReading: 'คิว', meaning: 'เก้า' },
  { word: 'じゅう', kanji: '十', romaji: 'juu', thaiReading: 'จู', meaning: 'สิบ' },
  { word: 'ひゃく', kanji: '百', romaji: 'hyaku', thaiReading: 'เฮียกุ', meaning: 'ร้อย' },
  { word: 'せん', kanji: '千', romaji: 'sen', thaiReading: 'เซ็น', meaning: 'พัน' },
  { word: 'まん', kanji: '万', romaji: 'man', thaiReading: 'มัง', meaning: 'หมื่น' },

  // คำศัพท์ทั่วไปเพิ่มเติม
  { word: 'おんがく', kanji: '音楽', romaji: 'ongaku', thaiReading: 'องกากุ', meaning: 'ดนตรี' },
  { word: 'えいが', kanji: '映画', romaji: 'eiga', thaiReading: 'เอกะ', meaning: 'ภาพยนตร์' },
  { word: 'しゃしん', kanji: '写真', romaji: 'shashin', thaiReading: 'ชาชิน', meaning: 'รูปถ่าย' },
  { word: 'てがみ', kanji: '手紙', romaji: 'tegami', thaiReading: 'เทกามิ', meaning: 'จดหมาย' },
  { word: 'さんぽ', kanji: '散歩', romaji: 'sanpo', thaiReading: 'ซัมโปะ', meaning: 'เดินเล่น' },
  { word: 'スポーツ', romaji: 'supootsu', thaiReading: 'สึโปทสึ', meaning: 'กีฬา' },
  { word: 'テニス', romaji: 'tenisu', thaiReading: 'เทนิสุ', meaning: 'เทนนิส' },
  { word: 'サッカー', romaji: 'sakkaa', thaiReading: 'ซักก้า', meaning: 'ฟุตบอล' },
  { word: 'くつ', kanji: '靴', romaji: 'kutsu', thaiReading: 'คุทสึ', meaning: 'รองเท้า' },
  { word: 'ふく', kanji: '服', romaji: 'fuku', thaiReading: 'ฟุกุ', meaning: 'เสื้อผ้า' },
  { word: 'さいふ', kanji: '財布', romaji: 'saifu', thaiReading: 'ไซฟุ', meaning: 'กระเป๋าสตางค์' },
  { word: 'ぼうし', kanji: '帽子', romaji: 'boushi', thaiReading: 'โบชิ', meaning: 'หมวก' },
  { word: 'めがね', kanji: '眼鏡', romaji: 'megane', thaiReading: 'เมกาเนะ', meaning: 'แว่นตา' },
  { word: 'かさ', kanji: '傘', romaji: 'kasa', thaiReading: 'คาซะ', meaning: 'ร่ม' },
  { word: 'かぎ', romaji: 'kagi', thaiReading: 'คากิ', meaning: 'กุญแจ' },
  { word: 'はし', romaji: 'hashi', thaiReading: 'ฮาชิ', meaning: 'ตะเกียบ/สะพาน' },
  { word: 'コップ', romaji: 'koppu', thaiReading: 'คอปปุ', meaning: 'แก้วน้ำ' },
  { word: 'さら', kanji: '皿', romaji: 'sara', thaiReading: 'ซาระ', meaning: 'จาน' },
  { word: 'れいぞうこ', kanji: '冷蔵庫', romaji: 'reizouko', thaiReading: 'เรโซโกะ', meaning: 'ตู้เย็น' },
  { word: 'せんたくき', kanji: '洗濯機', romaji: 'sentakuki', thaiReading: 'เซนตากุกิ', meaning: 'เครื่องซักผ้า' },
  { word: 'そうじ', kanji: '掃除', romaji: 'souji', thaiReading: 'โซจิ', meaning: 'ทำความสะอาด' },
  { word: 'りょうり', kanji: '料理', romaji: 'ryouri', thaiReading: 'เรียวริ', meaning: 'อาหาร/ทำอาหาร' },
  { word: 'かいもの', kanji: '買い物', romaji: 'kaimono', thaiReading: 'ไคโมโนะ', meaning: 'ซื้อของ' }
];
