
import { Vocabulary } from './types.ts';

export const VOCAB_N5: Vocabulary[] = [
  // --- กริยา (Verbs) - ต่อเนื่องจากเดิม ---
  { word: 'あう', kanji: '会う', romaji: 'au', thaiReading: 'อาอุ', meaning: 'พบ/เจอ' },
  { word: 'あく', kanji: '開く', romaji: 'aku', thaiReading: 'อากุ', meaning: 'เปิด (ประตูเปิดเอง)' },
  { word: 'あける', kanji: '開ける', romaji: 'akeru', thaiReading: 'อาเกรุ', meaning: 'เปิด (เปิดประตู)' },
  { word: 'あげる', kanji: '上げる', romaji: 'ageru', thaiReading: 'อาเกรุ', meaning: 'ให้/ยกขึ้น' },
  { word: 'あそぶ', kanji: '遊ぶ', romaji: 'asobu', thaiReading: 'อาโซบุ', meaning: 'เล่น' },
  { word: 'あらう', kanji: '洗う', romaji: 'arau', thaiReading: 'อาเรา', meaning: 'ล้าง' },
  { word: 'ある', romaji: 'aru', thaiReading: 'อารุ', meaning: 'มี/อยู่ (สิ่งของ)' },
  { word: 'あるく', kanji: '歩く', romaji: 'aruku', thaiReading: 'อารุกุ', meaning: 'เดิน' },
  { word: 'いう', kanji: '言う', romaji: 'iu', thaiReading: 'อิอุ', meaning: 'พูด' },
  { word: 'いく', kanji: '行く', romaji: 'iku', thaiReading: 'อิกุ', meaning: 'ไป' },
  { word: 'いる', romaji: 'iru', thaiReading: 'อิรุ', meaning: 'มี/อยู่ (คน/สัตว์)' },
  { word: 'いれる', kanji: '入れる', romaji: 'ireru', thaiReading: 'อิเระรุ', meaning: 'ใส่' },
  { word: 'うたう', kanji: '歌う', romaji: 'utau', thaiReading: 'อูตาอุ', meaning: 'ร้องเพลง' },
  { word: 'うまれる', kanji: '生まれる', romaji: 'umareru', thaiReading: 'อูมาเระรุ', meaning: 'เกิด' },
  { word: 'うる', kanji: '売る', romaji: 'uru', thaiReading: 'อูรุ', meaning: 'ขาย' },
  { word: 'おきる', kanji: '起きる', romaji: 'okiru', thaiReading: 'โอกิรุ', meaning: 'ตื่น/ลุกขึ้น' },
  { word: 'おく', kanji: '置く', romaji: 'oku', thaiReading: 'โอกุ', meaning: 'วาง' },
  { word: 'おくる', kanji: '送る', romaji: 'okuru', thaiReading: 'โอกุรุ', meaning: 'ส่ง' },
  { word: 'おしえる', kanji: '教える', romaji: 'oshieru', thaiReading: 'โอชิเอะรุ', meaning: 'สอน' },
  { word: 'おす', kanji: '押す', romaji: 'osu', thaiReading: 'โอสุ', meaning: 'กด/ผลัก' },
  { word: 'おぼえる', kanji: '覚える', romaji: 'oboeru', thaiReading: 'โอโบเอะรุ', meaning: 'จำ' },
  { word: 'およぐ', kanji: '泳ぐ', romaji: 'oyogu', thaiReading: 'โอยอกุ', meaning: 'ว่ายน้ำ' },
  { word: 'おりる', kanji: '降りる', romaji: 'oriru', thaiReading: 'โอริรุ', meaning: 'ลง (รถ/เขา)' },
  { word: 'おわる', kanji: '終わる', romaji: 'owaru', thaiReading: 'โอวารุ', meaning: 'เสร็จ/จบ' },
  { word: 'かう', kanji: '買う', romaji: 'kau', thaiReading: 'คาอุ', meaning: 'ซื้อ' },
  { word: 'かえす', kanji: '返す', romaji: 'kaesu', thaiReading: 'คาเอสุ', meaning: 'คืน' },
  { word: 'かえる', kanji: '帰る', romaji: 'kaeru', thaiReading: 'คาเอรุ', meaning: 'กลับ' },
  { word: 'かかる', romaji: 'kakaru', thaiReading: 'คาการุ', meaning: 'ใช้เวลา/เสียเงิน' },
  { word: 'かく', kanji: '書く', romaji: 'kaku', thaiReading: 'คากุ', meaning: 'เขียน' },
  { word: 'かける', romaji: 'kakeru', thaiReading: 'คาเระรุ', meaning: 'แขวน/โทรศัพท์' },
  { word: 'かす', kanji: '貸す', romaji: 'kasu', thaiReading: 'คาซุ', meaning: 'ให้ยืม' },
  { word: 'かぶる', romaji: 'kaburu', thaiReading: 'คาบุรุ', meaning: 'สวม (หมวก)' },
  { word: 'かりる', kanji: '借りる', romaji: 'kariru', thaiReading: 'คาริรุ', meaning: 'ขอยืม' },
  { word: 'きく', kanji: '聞く', romaji: 'kiku', thaiReading: 'คิกุ', meaning: 'ฟัง/ถาม' },
  { word: 'きる', kanji: '切る', romaji: 'kiru', thaiReading: 'คิรุ', meaning: 'ตัด' },
  { word: 'きる', kanji: '着る', romaji: 'kiru', thaiReading: 'คิรุ', meaning: 'สวมใส่ (เสื้อ)' },
  { word: 'くる', kanji: '来る', romaji: 'kuru', thaiReading: 'คุรุ', meaning: 'มา' },
  { word: 'けす', kanji: '消す', romaji: 'kesu', thaiReading: 'เคซุ', meaning: 'ปิดไฟ/ลบ' },
  { word: 'こたえる', kanji: '答える', romaji: 'kotaeru', thaiReading: 'โคตาเอะรุ', meaning: 'ตอบ' },
  { word: 'こまる', kanji: '困る', romaji: 'komaru', thaiReading: 'โคมาารุ', meaning: 'เดือดร้อน' },
  { word: 'さく', kanji: '咲く', romaji: 'saku', thaiReading: 'สากุ', meaning: 'บาน' },
  { word: 'さす', romaji: 'sasu', thaiReading: 'ซาสุ', meaning: 'กาง (ร่ม)' },
  { word: 'しめる', kanji: '閉める', romaji: 'shimeru', thaiReading: 'ชิเมะรุ', meaning: 'ปิด' },
  { word: 'しぬ', kanji: '死ぬ', romaji: 'shinu', thaiReading: 'ชินุ', meaning: 'ตาย' },
  { word: 'しる', kanji: '知る', romaji: 'shiru', thaiReading: 'ชิรุ', meaning: 'รู้จัก/รู้' },
  { word: 'すう', kanji: '吸う', romaji: 'suu', thaiReading: 'ซู', meaning: 'สูบ/ดูด' },
  { word: 'すむ', kanji: '住む', romaji: 'sumu', thaiReading: 'ซุมุ', meaning: 'อาศัยอยู่' },
  { word: 'する', romaji: 'suru', thaiReading: 'ซุรุ', meaning: 'ทำ' },
  { word: 'すわる', kanji: '座る', romaji: 'suwaru', thaiReading: 'ซุวารุ', meaning: 'นั่ง' },
  { word: 'だす', kanji: '出す', romaji: 'dasu', thaiReading: 'ดาสุ', meaning: 'ส่ง/เอาออก' },
  { word: 'たつ', kanji: '立つ', romaji: 'tatsu', thaiReading: 'ทัทสึ', meaning: 'ยืน' },
  { word: 'たのむ', kanji: '頼む', romaji: 'tanomu', thaiReading: 'ทาโนมุ', meaning: 'ขอร้อง/สั่ง' },
  { word: 'たべる', kanji: '食べる', romaji: 'taberu', thaiReading: 'ทาเบรุ', meaning: 'กิน' },
  { word: 'つかう', kanji: '使う', romaji: 'tsukau', thaiReading: 'ทสึกาอุ', meaning: 'ใช้' },
  { word: 'つかれる', kanji: '疲れる', romaji: 'tsukareru', thaiReading: 'ทสึกาเระรุ', meaning: 'เหนื่อย' },
  { word: 'つく', kanji: '着く', romaji: 'tsuku', thaiReading: 'ทสึคุ', meaning: 'ถึง (ที่หมาย)' },
  { word: 'つくる', kanji: '作る', romaji: 'tsukuru', thaiReading: 'ทสึกุรุ', meaning: 'ทำ/ผลิต' },
  { word: 'つける', romaji: 'つける', thaiReading: 'ทสึเกะรุ', meaning: 'เปิดไฟ' },
  { word: 'つとめる', kanji: '勤める', romaji: 'tsutomeru', thaiReading: 'ทสึโตเมะรุ', meaning: 'ทำงานที่...' },
  { word: 'とぶ', kanji: '飛ぶ', romaji: 'tobu', thaiReading: 'โทบุ', meaning: 'บิน/กระโดด' },
  { word: 'とまる', kanji: '止まる', romaji: 'tomaru', thaiReading: 'โทมารุ', meaning: 'หยุด' },
  { word: 'とる', kanji: '取る', romaji: 'toru', thaiReading: 'โทรุ', meaning: 'หยิบ/จับ' },
  { word: 'とる', kanji: '撮る', romaji: 'toru', thaiReading: 'โทรุ', meaning: 'ถ่ายรูป' },
  { word: 'なく', kanji: '鳴く', romaji: 'naku', thaiReading: 'นากุ', meaning: 'ร้อง (สัตว์)' },
  { word: 'ならぶ', kanji: '並ぶ', romaji: 'narabu', thaiReading: 'นาราบุ', meaning: 'เข้าแถว' },
  { word: 'ならう', kanji: '習う', romaji: 'narau', thaiReading: 'นาราว', meaning: 'เรียน' },
  { word: 'なる', romaji: 'naru', thaiReading: 'naru', meaning: 'กลายเป็น' },
  { word: 'ぬぐ', kanji: '脱ぐ', romaji: 'nugu', thaiReading: 'นุกุ', meaning: 'ถอด' },
  { word: 'ねる', kanji: '寝る', romaji: 'neru', thaiReading: 'เนรุ', meaning: 'นอน' },
  { word: 'のぼる', kanji: '登る', romaji: 'noboru', thaiReading: 'โนโบรุ', meaning: 'ปีน' },
  { word: 'のむ', kanji: '飲む', romaji: 'nomu', thaiReading: 'โนมุ', meaning: 'ดื่ม' },
  { word: 'のる', kanji: '乗る', romaji: 'noru', thaiReading: 'โนรุ', meaning: 'ขึ้นรถ' },
  { word: 'はいる', kanji: '入る', romaji: 'hairu', thaiReading: 'ไฮรุ', meaning: 'เข้า' },
  { word: 'はく', kanji: '履く', romaji: 'haku', thaiReading: 'ฮากุ', meaning: 'สวม (รองเท้า/กางเกง)' },
  { word: 'はたらく', kanji: '働く', romaji: 'hataraku', thaiReading: 'ฮาตารากุ', meaning: 'ทำงาน' },
  { word: 'はなす', kanji: '話す', romaji: 'hanasu', thaiReading: 'ฮานาสุ', meaning: 'พูดคุย' },
  { word: 'はる', kanji: '貼る', romaji: 'haru', thaiReading: 'ฮารุ', meaning: 'แปะ/ติด' },
  { word: 'はれ', kanji: '晴れ', romaji: 'hare', thaiReading: 'ฮาเระ', meaning: 'อากาศแจ่มใส' },
  { word: 'ひく', kanji: '引く', romaji: 'hiku', thaiReading: 'ฮิกุ', meaning: 'ดึง/ลาก/เล่นเครื่องสาย' },
  { word: 'ひく', kanji: '弾く', romaji: 'hiku', thaiReading: 'ฮิกุ', meaning: 'เล่น (เปียโน)' },
  { word: 'ふく', kanji: '吹く', romaji: 'fuku', thaiReading: 'ฟุกุ', meaning: 'เป่า/พัด' },
  { word: 'ふる', kanji: '降る', romaji: 'furu', thaiReading: 'ฟุรุ', meaning: 'ตก (ฝน/หิมะ)' },
  { word: 'まがる', kanji: '曲がる', romaji: 'magaru', thaiReading: 'มาการุ', meaning: 'เลี้ยว' },
  { word: 'まつ', kanji: '待つ', romaji: 'matsu', thaiReading: 'มัทสึ', meaning: 'รอ' },
  { word: 'みがく', kanji: '磨く', romaji: 'migaku', thaiReading: 'มิกากุ', meaning: 'แปรง/ขัด' },
  { word: 'みせる', kanji: '見せる', romaji: 'miseru', thaiReading: 'มิเซะรุ', meaning: 'ให้ดู' },
  { word: 'みる', kanji: '見る', romaji: 'miru', thaiReading: 'มิรุ', meaning: 'ดู' },
  { word: 'もつ', kanji: '持つ', romaji: 'motsu', thaiReading: 'โมทสึ', meaning: 'ถือ' },
  { word: 'やすむ', kanji: '休む', romaji: 'yasumu', thaiReading: 'ยาซูมุ', meaning: 'พักผ่อน/หยุด' },
  { word: 'やる', romaji: 'yaru', thaiReading: 'ยารุ', meaning: 'ทำ/ให้' },
  { word: 'よぶ', kanji: '呼ぶ', romaji: 'yobu', thaiReading: 'โยบุ', meaning: 'เรียก' },
  { word: 'よむ', kanji: '読む', romaji: 'yomu', thaiReading: 'โยมุ', meaning: 'อ่าน' },
  { word: 'わかる', kanji: '分かる', romaji: 'wakaru', thaiReading: 'วากาวุ', meaning: 'เข้าใจ' },
  { word: 'わすれる', kanji: '忘れる', romaji: 'wasureru', thaiReading: 'วาซูเระรุ', meaning: 'ลืม' },
  { word: 'わたす', kanji: '渡す', romaji: 'watasu', thaiReading: 'วาตาซุ', meaning: 'ส่งมอบ' },
  { word: 'わたる', kanji: '渡る', romaji: 'wataru', thaiReading: 'วาตารุ', meaning: 'ข้าม' },

  // --- คุณศัพท์ (Adjectives) ---
  { word: 'あかるい', kanji: '明るい', romaji: 'akarui', thaiReading: 'อาการุ่ย', meaning: 'สว่าง' },
  { word: 'あたたかい', kanji: '温かい', romaji: 'atatakai', thaiReading: 'อาตากาไก้', meaning: 'อบอุ่น' },
  { word: 'あたらしい', kanji: '新しい', romaji: 'atarashii', thaiReading: 'อาตาราชี่', meaning: 'ใหม่' },
  { word: 'あつい', kanji: '暑い', romaji: 'atsui', thaiReading: 'อาทสึ่ย', meaning: 'ร้อน (อากาศ)' },
  { word: 'あつい', kanji: '熱い', romaji: 'atsui', thaiReading: 'อาทสึ่ย', meaning: 'ร้อน (ของร้อน)' },
  { word: 'あつい', kanji: '厚い', romaji: 'atsui', thaiReading: 'อาทสึ่ย', meaning: 'หนา' },
  { word: 'あぶない', kanji: '危ない', romaji: 'abunai', thaiReading: 'อาบูไน้', meaning: 'อันตราย' },
  { word: 'あまい', kanji: '甘い', romaji: 'amai', thaiReading: 'อาไม', meaning: 'หวาน' },
  { word: 'いい', romaji: 'ii', thaiReading: 'อี้', meaning: 'ดี' },
  { word: 'いそがしい', kanji: '忙しい', romaji: 'isogashii', thaiReading: 'อิโซกาชี่', meaning: 'ยุ่ง' },
  { word: 'いたい', kanji: '痛い', romaji: 'itai', thaiReading: 'อิไต้', meaning: 'เจ็บ/ปวด' },
  { word: 'うすい', kanji: '薄い', romaji: 'usui', thaiReading: 'อูซุ่ย', meaning: 'บาง/จืด' },
  { word: 'うるさい', romaji: 'urusai', thaiReading: 'อูรูไซ้', meaning: 'หนวกหู' },
  { word: 'おいしい', romaji: 'oishii', thaiReading: 'โออิชี่', meaning: 'อร่อย' },
  { word: 'おおきい', kanji: '大きい', romaji: 'ookii', thaiReading: 'โอกี้', meaning: 'ใหญ่' },
  { word: 'おそい', kanji: '遅い', romaji: 'osoi', thaiReading: 'โอโซ่ย', meaning: 'ช้า/สาย' },
  { word: 'おもい', kanji: '重い', romaji: 'omoi', thaiReading: 'โอโม่ย', meaning: 'หนัก' },
  { word: 'おもしろい', romaji: 'omoshiroi', thaiReading: 'โอโมชิโร่ย', meaning: 'สนุก/น่าสนใจ' },
  { word: 'からい', kanji: '辛い', romaji: 'karai', thaiReading: 'กาไร่', meaning: 'เผ็ด' },
  { word: 'かるい', kanji: '軽い', romaji: 'karui', thaiReading: 'การุ่ย', meaning: 'เบา' },
  { word: 'かわいい', romaji: 'kawaii', thaiReading: 'คาวาอี้', meaning: 'น่ารัก' },
  { word: 'きいろい', kanji: '黄色い', romaji: 'kiiroi', thaiReading: 'คิอิโร่ย', meaning: 'สีเหลือง' },
  { word: 'きたない', kanji: '汚い', romaji: 'kitanai', thaiReading: 'คิตาไน้', meaning: 'สกปรก' },
  { word: 'くらい', kanji: '暗い', romaji: 'kurai', thaiReading: 'กูไร่', meaning: 'มืด' },
  { word: 'くろい', kanji: '黒い', romaji: 'kuroi', thaiReading: 'คุโร่ย', meaning: 'สีดำ' },
  { word: 'さむい', kanji: '寒い', romaji: 'samui', thaiReading: 'ซามุ่ย', meaning: 'หนาว' },
  { word: 'しおからい', romaji: 'shiokarai', thaiReading: 'ชิโอกาไร่', meaning: 'เค็ม' },
  { word: 'しろい', kanji: '白い', romaji: 'shiroi', thaiReading: 'ชิโร่ย', meaning: 'สีขาว' },
  { word: 'すくない', kanji: '少ない', romaji: 'sukunai', thaiReading: 'ซูกูไน้', meaning: 'น้อย' },
  { word: 'すずしい', kanji: '涼しい', romaji: 'suzushii', thaiReading: 'ซูซูชี่', meaning: 'เย็นสบาย' },
  { word: 'せまい', kanji: '狭い', romaji: 'semai', thaiReading: 'เซไม', meaning: 'แคบ' },
  { word: 'たかい', kanji: '高い', romaji: 'takai', thaiReading: 'ทาก้าย', meaning: 'สูง/แพง' },
  { word: 'たのしい', kanji: '楽しい', romaji: 'tanoshii', thaiReading: 'ตาโนชี่', meaning: 'สนุกสนาน' },
  { word: 'ちいさい', kanji: '小さい', romaji: 'chiisai', thaiReading: 'ชิไซ้', meaning: 'เล็ก' },
  { word: 'ちかい', kanji: '近い', romaji: 'chikai', thaiReading: 'จิไก้', meaning: 'ใกล้' },
  { word: 'つまらない', romaji: 'tsumaranai', thaiReading: 'ทสึมาราไน้', meaning: 'น่าเบื่อ' },
  { word: 'つめたい', kanji: '冷たい', romaji: 'tsumetai', thaiReading: 'ทสึเมไต', meaning: 'เย็น (สัมผัส)' },
  { word: 'つよい', kanji: '強い', romaji: 'tsuyoi', thaiReading: 'ทสึโย่ย', meaning: 'แข็งแกร่ง' },
  { word: 'とおい', kanji: '遠い', romaji: 'tooi', thaiReading: 'โต้อิ', meaning: 'ไกล' },
  { word: 'ながい', kanji: '長い', romaji: 'nagai', thaiReading: 'นาก้าย', meaning: 'ยาว' },
  { word: 'にぎやか', romaji: 'nigiyaka', thaiReading: 'นิกิยากะ', meaning: 'ครึกครื้น' },
  { word: 'ぬるい', romaji: 'nurui', thaiReading: 'นูรุ่ย', meaning: 'อุ่น (ไม่ร้อนไม่เย็น)' },
  { word: 'はやい', kanji: '早い', romaji: 'hayai', thaiReading: 'ฮาย้าย', meaning: 'เร็ว/เช้า' },
  { word: 'はやい', kanji: '速い', romaji: 'hayai', thaiReading: 'ฮาย้าย', meaning: 'เร็ว (ความเร็ว)' },
  { word: 'ひくい', kanji: '低い', romaji: 'hikui', thaiReading: 'ฮิกุ่ย', meaning: 'เตี้ย' },
  { word: 'ひろい', kanji: '広い', romaji: 'hiroi', thaiReading: 'ฮิโร่ย', meaning: 'กว้าง' },
  { word: 'ふとい', kanji: '太い', romaji: 'futoi', thaiReading: 'ฟุโต่ย', meaning: 'หนา/อ้วน' },
  { word: 'ふるい', kanji: '古い', romaji: 'furui', thaiReading: 'ฟุรุ่ย', meaning: 'เก่า' },
  { word: 'ほしい', kanji: '欲しい', romaji: 'hoshii', thaiReading: 'โฮชี่', meaning: 'ต้องการ' },
  { word: 'ほそい', kanji: '細い', romaji: 'hosoi', thaiReading: 'โฮโซ่ย', meaning: 'ผอม/บาง' },
  { word: 'まずい', romaji: 'mazui', thaiReading: 'มาซุ่ย', meaning: 'ไม่อร่อย' },
  { word: 'まるい', kanji: '丸い', romaji: 'marui', thaiReading: 'มารุ่ย', meaning: 'กลม' },
  { word: 'みじかい', kanji: '短い', romaji: 'mijikai', thaiReading: 'มิจิก้าย', meaning: 'สั้น' },
  { word: 'むずかしい', kanji: '難しい', romaji: 'muzukashii', thaiReading: 'มุซุกาชี่', meaning: 'ยาก' },
  { word: 'やさしい', romaji: 'yasashii', thaiReading: 'ยาซาชี่', meaning: 'ง่าย/ใจดี' },
  { word: 'やすい', kanji: '安い', romaji: 'yasui', thaiReading: 'ยาซุ่ย', meaning: 'ถูก' },
  { word: 'ゆうめい', kanji: '有名', romaji: 'yuumei', thaiReading: 'ยูเม', meaning: 'ชื่อดัง' },
  { word: 'よい', romaji: 'yoi', thaiReading: 'โย่ย', meaning: 'ดี' },
  { word: 'よわい', kanji: '弱い', romaji: 'yowai', thaiReading: 'โยไว่', meaning: 'อ่อนแอ' },
  { word: 'わかい', kanji: '若い', romaji: 'wakai', thaiReading: 'วาก้าย', meaning: 'หนุ่มสาว' },
  { word: 'わるい', kanji: '悪い', romaji: 'warui', thaiReading: 'วารุ่ย', meaning: 'เลว/ไม่ดี' },

  // --- คำนาม: ร่างกาย (Body) ---
  { word: 'あたま', kanji: '頭', romaji: 'atama', thaiReading: 'อาตามะ', meaning: 'หัว' },
  { word: 'かお', kanji: '顔', romaji: 'kao', thaiReading: 'กาโอ้', meaning: 'ใบหน้า' },
  { word: 'め', kanji: '目', romaji: 'me', thaiReading: 'เมะ', meaning: 'ตา' },
  { word: 'みみ', kanji: '耳', romaji: 'mimi', thaiReading: 'มิมิ', meaning: 'หู' },
  { word: 'はな', kanji: '鼻', romaji: 'hana', thaiReading: 'ฮานะ', meaning: 'จมูก' },
  { word: 'くち', kanji: '口', romaji: 'kuchi', thaiReading: 'คุจิ', meaning: 'ปาก' },
  { word: 'は', kanji: '歯', romaji: 'ha', thaiReading: 'ฮะ', meaning: 'ฟัน' },
  { word: 'て', kanji: '手', romaji: 'te', thaiReading: 'เทะ', meaning: 'มือ' },
  { word: 'あし', kanji: '足', romaji: 'ashi', thaiReading: 'อาชิ', meaning: 'เท้า/ขา' },
  { word: 'จากดา', kanji: '体', romaji: 'karada', thaiReading: 'การาดะ', meaning: 'ร่างกาย' },
  { word: 'おなか', romaji: 'onaka', thaiReading: 'โอนากะ', meaning: 'ท้อง' },
  { word: 'こころ', kanji: '心', romaji: 'kokoro', thaiReading: 'โคโคโระ', meaning: 'หัวใจ/จิตใจ' },
  { word: 'こえ', kanji: '声', romaji: 'koe', thaiReading: 'โกเอะ', meaning: 'เสียง' },

  // --- คำนาม: ครอบครัว (Family) ---
  { word: 'かぞく', kanji: '家族', romaji: 'kazoku', thaiReading: 'คาโซกุ', meaning: 'ครอบครัว' },
  { word: 'ちち', kanji: '父', romaji: 'chichi', thaiReading: 'ชิชิ', meaning: 'พ่อ (ของฉัน)' },
  { word: 'はは', kanji: '母', romaji: 'haha', thaiReading: 'ฮาฮะ', meaning: 'แม่ (ของฉัน)' },
  { word: 'おとうさん', kanji: 'お父さん', romaji: 'otousan', thaiReading: 'โอโตซัง', meaning: 'คุณพ่อ' },
  { word: 'おかあさん', kanji: 'お母さん', romaji: 'okaasan', thaiReading: 'โอกาซัง', meaning: 'คุณแม่' },
  { word: 'あに', kanji: '兄', romaji: 'ani', thaiReading: 'อานิ', meaning: 'พี่ชาย (ของฉัน)' },
  { word: 'あね', kanji: '姉', romaji: 'ane', thaiReading: 'อาเนะ', meaning: 'พี่สาว (ของฉัน)' },
  { word: 'おにいさん', romaji: 'oniisan', thaiReading: 'โอนีซัง', meaning: 'พี่ชายคนอื่น' },
  { word: 'おねえさん', romaji: 'oneesan', thaiReading: 'โอเนซัง', meaning: 'พี่สาวคนอื่น' },
  { word: 'おとうと', kanji: '弟', romaji: 'otouto', thaiReading: 'โอโตโตะ', meaning: 'น้องชาย' },
  { word: 'いもうと', kanji: '妹', romaji: 'imouto', thaiReading: 'อิโมโตะ', meaning: 'น้องสาว' },
  { word: 'きょうだい', kanji: '兄弟', romaji: 'kyoudai', thaiReading: 'เกียวได', meaning: 'พี่น้อง' },
  { word: 'おっと', kanji: '夫', romaji: 'otto', thaiReading: 'อทโตะ', meaning: 'สามี (ของฉัน)' },
  { word: 'つま', kanji: '妻', romaji: 'tsuma', thaiReading: 'ทสึมะ', meaning: 'ภรรยา (ของฉัน)' },
  { word: 'しゅじん', kanji: '主人', romaji: 'shujin', thaiReading: 'ชูจิน', meaning: 'สามี' },
  { word: 'かない', kanji: '家内', romaji: 'kanai', thaiReading: 'กาไน', meaning: 'ภรรยา' },

  // --- คำนาม: เวลา (Time) ---
  { word: 'いま', kanji: '今', romaji: 'ima', thaiReading: 'อิมา', meaning: 'ตอนนี้' },
  { word: 'あさ', kanji: '朝', romaji: 'asa', thaiReading: 'อาสะ', meaning: 'เช้า' },
  { word: 'ひる', kanji: '昼', romaji: 'hiru', thaiReading: 'ฮิรุ', meaning: 'กลางวัน' },
  { word: 'ばん', kanji: '晩', romaji: 'ban', thaiReading: 'บัง', meaning: 'เย็น' },
  { word: 'よる', kanji: '夜', romaji: 'yoru', thaiReading: 'โยรุ', meaning: 'กลางคืน' },
  { word: 'ゆうべ', romaji: 'yuube', thaiReading: 'ยูเบะ', meaning: 'เมื่อคืน' },
  { word: 'あした', kanji: '明日', romaji: 'ashita', thaiReading: 'อาชิตะ', meaning: 'พรุ่งนี้' },
  { word: 'きょう', kanji: '今日', romaji: 'kyou', thaiReading: 'เคียว', meaning: 'วันนี้' },
  { word: 'きのう', kanji: '昨日', romaji: 'kinou', thaiReading: 'คิโน', meaning: 'เมื่อวาน' },
  { word: 'あさって', romaji: 'asatte', thaiReading: 'อาซัตเตะ', meaning: 'มะรืนนี้' },
  { word: 'おととい', romaji: 'ototoi', thaiReading: 'โอโตโตย', meaning: 'เมื่อวานซืน' },
  { word: 'さき', kanji: '先', romaji: 'saki', thaiReading: 'ซากิ', meaning: 'ก่อน/ล่วงหน้า' },
  { word: 'あと', kanji: '後', romaji: 'ato', thaiReading: 'อาโตะ', meaning: 'หลัง/ทีหลัง' },
  { word: 'じかん', kanji: '時間', romaji: 'jikan', thaiReading: 'จิกัง', meaning: 'เวลา' },

  // --- เดือน (Months) ---
  { word: 'いちがつ', kanji: '一月', romaji: 'ichigatsu', thaiReading: 'อิจิกัตสึ', meaning: 'มกราคม' },
  { word: 'にがつ', kanji: '二月', romaji: 'nigatsu', thaiReading: 'นิกัตสึ', meaning: 'กุมภาพันธ์' },
  { word: 'さんがつ', kanji: '三月', romaji: 'sangatsu', thaiReading: 'ซังกัตสึ', meaning: 'มีนาคม' },
  { word: 'しがつ', kanji: '四月', romaji: 'shigatsu', thaiReading: 'ชิกัตสึ', meaning: 'เมษายน' },
  { word: 'ごがつ', kanji: '五月', romaji: 'gogatsu', thaiReading: 'โกกัตสึ', meaning: 'พฤษภาคม' },
  { word: 'ろくがつ', kanji: '六月', romaji: 'rokugatsu', thaiReading: 'โรกุกัตสึ', meaning: 'มิถุนายน' },
  { word: 'しちがつ', kanji: '七月', romaji: 'shichigatsu', thaiReading: 'ชิจิกัตสึ', meaning: 'กรกฎาคม' },
  { word: 'はちがつ', kanji: '八月', romaji: 'hachigatsu', thaiReading: 'ฮาจิกัตสึ', meaning: 'สิงหาคม' },
  { word: 'くがつ', kanji: '九月', romaji: 'kugatsu', thaiReading: 'คุกัตสึ', meaning: 'กันยายน' },
  { word: 'じゅうがつ', kanji: '十月', romaji: 'juugatsu', thaiReading: 'จูกัตสึ', meaning: 'ตุลาคม' },
  { word: 'じゅういちがつ', kanji: '十一月', romaji: 'juuichigatsu', thaiReading: 'จูอิจิกัตสึ', meaning: 'พฤศจิกายน' },
  { word: 'じゅうにがつ', kanji: '十二月', romaji: 'juunigatsu', thaiReading: 'จูนิกัตสึ', meaning: 'ธันวาคม' },

  // --- วันที่ (Dates of the Month) ---
  { word: 'ついたち', kanji: '一日', romaji: 'tsuitachi', thaiReading: 'ทสึอิตาจิ', meaning: 'วันที่ 1' },
  { word: 'ふつか', kanji: '二日', romaji: 'futsuka', thaiReading: 'ฟุตสึ่กะ', meaning: 'วันที่ 2' },
  { word: 'みっか', kanji: '三日', romaji: 'mikka', thaiReading: 'มิกกะ', meaning: 'วันที่ 3' },
  { word: 'よっか', kanji: '四日', romaji: 'yokka', thaiReading: 'ยคกะ', meaning: 'วันที่ 4' },
  { word: 'いつか', kanji: '五日', romaji: 'itsuka', thaiReading: 'อิทสึกะ', meaning: 'วันที่ 5' },
  { word: 'むいか', kanji: '六日', romaji: 'muika', thaiReading: 'มุอิกะ', meaning: 'วันที่ 6' },
  { word: 'なのか', kanji: '七日', romaji: 'nanoka', thaiReading: 'นาโนกะ', meaning: 'วันที่ 7' },
  { word: 'ようか', kanji: '八日', romaji: 'youka', thaiReading: 'โยกะ', meaning: 'วันที่ 8' },
  { word: 'ここのか', kanji: '九日', romaji: 'kokonoka', thaiReading: 'โกโกโนกะ', meaning: 'วันที่ 9' },
  { word: 'とおか', kanji: '十日', romaji: 'tooka', thaiReading: 'โตกะ', meaning: 'วันที่ 10' },
  { word: 'はつか', kanji: '二十日', romaji: 'hatsuka', thaiReading: 'ฮัตสึกะ', meaning: 'วันที่ 20' },

  // --- วันในสัปดาห์ (Days of the week) ---
  { word: 'げつようび', kanji: '月曜日', romaji: 'getsuyoubi', thaiReading: 'เก็ตสึโยบิ', meaning: 'วันจันทร์' },
  { word: 'かようび', kanji: '火曜日', romaji: 'kayoubi', thaiReading: 'คาโยบิ', meaning: 'วันอังคาร' },
  { word: 'すいようび', kanji: '水曜日', romaji: 'suiyoubi', thaiReading: 'ซุยโยบิ', meaning: 'วันพุธ' },
  { word: 'もくようび', kanji: '木曜日', romaji: 'mokuyoubi', thaiReading: 'โมคุโยบิ', meaning: 'วันพฤหัสบดี' },
  { word: 'きんようび', kanji: '金曜日', romaji: 'kinyoubi', thaiReading: 'คินโยบิ', meaning: 'วันศุกร์' },
  { word: 'どようび', kanji: '土曜日', romaji: 'doyoubi', thaiReading: 'โดโยบิ', meaning: 'วันเสาร์' },
  { word: 'にちようび', kanji: '日曜日', romaji: 'nichiyoubi', thaiReading: 'นิจิโยบิ', meaning: 'วันอาทิตย์' },

  // --- สี (Colors) ---
  { word: 'あか', kanji: '赤', romaji: 'aka', thaiReading: 'อากะ', meaning: 'สีแดง' },
  { word: 'あお', kanji: '青', romaji: 'ao', thaiReading: 'อาโอะ', meaning: 'สีน้ำเงิน/ฟ้า' },
  { word: 'しろ', kanji: '白', romaji: 'shiro', thaiReading: 'ชิโระ', meaning: 'สีขาว' },
  { word: 'くろ', kanji: '黒', romaji: 'kuro', thaiReading: 'คุโระ', meaning: 'สีดำ' },
  { word: 'きいろ', kanji: '黄色', romaji: 'kiiro', thaiReading: 'คิอิโระ', meaning: 'สีเหลือง' },
  { word: 'みどり', kanji: '緑', romaji: 'midori', thaiReading: 'มิโดริ', meaning: 'สีเขียว' },
  { word: 'ちゃいろ', kanji: '茶色', romaji: 'chairo', thaiReading: 'ไชโระ', meaning: 'สีน้ำตาล' },
  { word: 'むらさき', kanji: '紫', romaji: 'murasaki', thaiReading: 'มุราซากิ', meaning: 'สีม่วง' },

  // --- ทิศทางและตำแหน่ง (Direction & Place) ---
  { word: 'うえ', kanji: '上', romaji: 'ue', thaiReading: 'อูเอะ', meaning: 'บน' },
  { word: 'した', kanji: '下', romaji: 'shita', thaiReading: 'ชิตะ', meaning: 'ล่าง' },
  { word: 'まえ', kanji: '前', romaji: 'mae', thaiReading: 'มาเอะ', meaning: 'หน้า' },
  { word: 'うしろ', kanji: '後ろ', romaji: 'ushiro', thaiReading: 'อูชิโระ', meaning: 'หลัง' },
  { word: 'みぎ', kanji: '右', romaji: 'migi', thaiReading: 'มิกิ', meaning: 'ขวา' },
  { word: 'ひだり', kanji: '左', romaji: 'hidari', thaiReading: 'ฮิดาริ', meaning: 'ซ้าย' },
  { word: 'なか', kanji: '中', romaji: 'naka', thaiReading: 'นากะ', meaning: 'ข้างใน' },
  { word: 'そと', kanji: '外', romaji: 'soto', thaiReading: 'โซโตะ', meaning: 'ข้างนอก' },
  { word: 'となり', romaji: 'tonari', thaiReading: 'โทนาริ', meaning: 'ข้างๆ' },
  { word: 'よこ', kanji: '横', romaji: 'yoko', thaiReading: 'โยโกะ', meaning: 'ด้านข้าง' },
  { word: 'そば', romaji: 'soba', thaiReading: 'โซบะ', meaning: 'ข้างๆ/ใกล้ๆ' },
  { word: 'あいだ', kanji: '間', romaji: 'aida', thaiReading: 'ไอดะ', meaning: 'ระหว่าง' },

  // --- สถานที่ (Places) ---
  { word: '가っこう', kanji: '学校', romaji: 'gakkou', thaiReading: 'กักโก', meaning: 'โรงเรียน' },
  { word: 'えき', kanji: '駅', romaji: 'eki', thaiReading: 'เอกิ', meaning: 'สถานีรถไฟ' },
  { word: 'びょういん', kanji: '病院', romaji: 'byouin', thaiReading: 'เบียวอิน', meaning: 'โรงพยาบาล' },
  { word: 'こうえん', kanji: '公園', romaji: 'kouen', thaiReading: 'โคเอ็น', meaning: 'สวนสาธารณะ' },
  { word: 'きっさてん', romaji: 'kissaten', thaiReading: 'คิสซาเต็น', meaning: 'ร้านกาแฟ' },
  { word: 'デパート', romaji: 'depaato', thaiReading: 'เดปาโตะ', meaning: 'ห้างสรรพสินค้า' },
  { word: 'まち', kanji: '町', romaji: 'machi', thaiReading: 'มาจิ', meaning: 'เมือง' },
  { word: 'むら', kanji: '村', romaji: 'mura', thaiReading: 'มุระ', meaning: 'หมู่บ้าน' },
  { word: 'やま', kanji: '山', romaji: 'yama', thaiReading: 'ยามะ', meaning: 'ภูเขา' },
  { word: 'かわ', kanji: '川', romaji: 'kawa', thaiReading: 'คาวะ', meaning: 'แม่น้ำ' },
  { word: 'うみ', kanji: '海', romaji: 'umi', thaiReading: 'อูมิ', meaning: 'ทะเล' },
  { word: 'そら', kanji: '空', romaji: 'sora', thaiReading: 'โซระ', meaning: 'ท้องฟ้า' },
  { word: 'みち', kanji: '道', romaji: 'michi', thaiReading: 'มิจิ', meaning: 'ถนน/ทาง' },
  { word: 'はし', kanji: '橋', romaji: 'hashi', thaiReading: 'ฮาชิ', meaning: 'สะพาน' },

  // --- ของกิน (Food & Drink) ---
  { word: 'みず', kanji: '水', romaji: 'mizu', thaiReading: 'มิซุ', meaning: 'น้ำ' },
  { word: 'おちゃ', kanji: 'お茶', romaji: 'ocha', thaiReading: 'โอจะ', meaning: 'ชา' },
  { word: 'おさけ', kanji: 'お酒', romaji: 'osake', thaiReading: 'โอสาเกะ', meaning: 'เหล้า' },
  { word: 'ごはん', kanji: 'ご飯', romaji: 'gohan', thaiReading: 'โกฮัง', meaning: 'ข้าว' },
  { word: 'にく', kanji: '肉', romaji: 'niku', thaiReading: 'นิกุ', meaning: 'เนื้อ' },
  { word: 'さかな', kanji: '魚', romaji: 'sakana', thaiReading: 'ซากานะ', meaning: 'ปลา' },
  { word: 'やさい', kanji: '野菜', romaji: 'yasai', thaiReading: 'ยาไซ', meaning: 'ผัก' },
  { word: 'くだもの', kanji: '果物', romaji: 'kudamono', thaiReading: 'คุดาโมโนะ', meaning: 'ผลไม้' },
  { word: 'りんご', romaji: 'ringo', thaiReading: 'ริงโกะ', meaning: 'แอปเปิ้ล' },
  { word: 'みかん', romaji: 'mikan', thaiReading: 'มิกัง', meaning: 'ส้ม' },
  { word: 'さとう', romaji: 'satou', thaiReading: 'ซาโต้', meaning: 'น้ำตาล' },
  { word: 'しお', kanji: '塩', romaji: 'shio', thaiReading: 'ชิโอะ', meaning: 'เกลือ' },
  { word: 'たまご', kanji: '卵', romaji: 'tamago', thaiReading: 'ทามาโกะ', meaning: 'ไข่' },
  { word: 'おかし', kanji: 'お菓子', romaji: 'okashi', thaiReading: 'โอกาชิ', meaning: 'ขนม' },
  { word: 'べんとう', kanji: '弁当', romaji: 'bentou', thaiReading: 'เบนโตะ', meaning: 'ข้าวกล่อง' },
  { word: 'りょうり', kanji: '料理', romaji: 'ryouri', thaiReading: 'เรียวริ', meaning: 'อาหาร/การทำอาหาร' },

  // --- สิ่งของ (Objects) ---
  { word: 'ほん', kanji: '本', romaji: 'hon', thaiReading: 'ฮง', meaning: 'หนังสือ' },
  { word: 'じしょ', kanji: '辞書', romaji: 'jisho', thaiReading: 'จิโชะ', meaning: 'พจนานุกรม' },
  { word: 'ざっし', kanji: '雑誌', romaji: 'zasshi', thaiReading: 'ซัสชิ', meaning: 'นิตยสาร' },
  { word: 'しんぶん', kanji: '新聞', romaji: 'shinbun', thaiReading: 'ชิมบุง', meaning: 'หนังสือพิมพ์' },
  { word: 'のーと', romaji: 'nooto', thaiReading: 'โนโตะ', meaning: 'สมุดบันทึก' },
  { word: 'かばん', romaji: 'kaban', thaiReading: 'คาบัง', meaning: 'กระเป๋า' },
  { word: 'かぎ', romaji: 'kagi', thaiReading: 'คากิ', meaning: 'กุญแจ' },
  { word: 'とけい', kanji: '時計', romaji: 'tokei', thaiReading: 'โทเค', meaning: 'นาฬิกา' },
  { word: 'でんわ', kanji: '電話', romaji: 'denwa', thaiReading: 'เดนวะ', meaning: 'โทรศัพท์' },
  { word: 'カメラ', romaji: 'kamera', thaiReading: 'คาเมร่า', meaning: 'กล้อง' },
  { word: 'くるま', kanji: '車', romaji: 'kuruma', thaiReading: 'คุรุมะ', meaning: 'รถยนต์' },
  { word: 'じてんしゃ', kanji: '自転車', romaji: 'jitensha', thaiReading: 'จิเทนฉะ', meaning: 'จักรยาน' },
  { word: 'かさ', kanji: '傘', romaji: 'kasa', thaiReading: 'คาซะ', meaning: 'ร่ม' },
  { word: 'くつ', kanji: '靴', romaji: 'kutsu', thaiReading: 'คุทสึ', meaning: 'รองเท้า' },
  { word: 'ふく', kanji: '服', romaji: 'fuku', thaiReading: 'ฟุกุ', meaning: 'เสื้อผ้า' },
  { word: 'さいふ', kanji: '財布', romaji: 'saifu', thaiReading: 'ไซฟุ', meaning: 'กระเป๋าสตางค์' },
  { word: 'きって', kanji: '切手', romaji: 'kitte', thaiReading: 'คิตเตะ', meaning: 'แสตมป์' },
  { word: 'はがき', romaji: 'hagaki', thaiReading: 'ฮากากิ', meaning: 'ไปรษณียบัตร' },
  { word: 'てがみ', kanji: '手紙', romaji: 'tegami', thaiReading: 'เทกามิ', meaning: 'จดหมาย' },

  // --- บุคคลและอาชีพ (People & Occupations) ---
  { word: 'ひと', kanji: '人', romaji: 'hito', thaiReading: 'ฮิโตะ', meaning: 'คน' },
  { word: 'こども', kanji: '子供', romaji: 'kodomo', thaiReading: 'โคโดโมะ', meaning: 'เด็ก' },
  { word: 'おとこ', kanji: '男', romaji: 'otoko', thaiReading: 'โอโตโกะ', meaning: 'ผู้ชาย' },
  { word: 'おんな', kanji: '女', romaji: 'onna', thaiReading: 'อนนะ', meaning: 'ผู้หญิง' },
  { word: 'がくせい', kanji: '学生', romaji: 'gakusei', thaiReading: 'กักเซ', meaning: 'นักเรียน' },
  { word: 'せんせい', kanji: '先生', romaji: 'sensei', thaiReading: 'เซ็นเซ', meaning: 'อาจารย์/ครู' },
  { word: 'いしゃ', kanji: '医者', romaji: 'isha', thaiReading: 'อิฉะ', meaning: 'หมอ' },
  { word: 'かいしゃいん', kanji: '会社員', romaji: 'kaishain', thaiReading: 'ไคไชอิน', meaning: 'พนักงานบริษัท' },
  { word: 'ぎんこういん', kanji: '銀行員', romaji: 'ginkouin', thaiReading: 'กินโกอิน', meaning: 'พนักงานธนาคาร' },
  { word: 'ともだち', kanji: '友達', romaji: 'tomodachi', thaiReading: 'โทโมดาจิ', meaning: 'เพื่อน' },
  { word: 'だれ', romaji: 'dare', thaiReading: 'ดาเระ', meaning: 'ใคร' },

  // --- คำถาม (Question Words) ---
  { word: 'なに', kanji: '何', romaji: 'nani', thaiReading: 'นานิ', meaning: 'อะไร' },
  { word: 'どこ', romaji: 'doko', thaiReading: 'โดโกะ', meaning: 'ที่ไหน' },
  { word: 'いつ', romaji: 'itsu', thaiReading: 'อิทสึ', meaning: 'เมื่อไหร่' },
  { word: 'どう', romaji: 'dou', thaiReading: 'โด', meaning: 'อย่างไร' },
  { word: 'どちら', romaji: 'dochira', thaiReading: 'โดจิระ', meaning: 'อันไหน/ทางไหน' },
  { word: 'どの', romaji: 'dono', thaiReading: 'โดโนะ', meaning: 'ไหน (ใช้นำหน้านาม)' },
  { word: 'いくら', romaji: 'ikura', thaiReading: 'อิกุระ', meaning: 'เท่าไหร่ (ราคา)' },
  { word: 'いくつ', romaji: 'ikutsu', thaiReading: 'อิกุทสึ', meaning: 'กี่อัน/อายุเท่าไหร่' },

  // --- คำวิเศษณ์เพิ่มเติม (More Adverbs) ---
  { word: 'とても', romaji: 'totemo', thaiReading: 'โทเทโมะ', meaning: 'มาก' },
  { word: 'あまり', romaji: 'amari', thaiReading: 'อามาริ', meaning: 'ไม่ค่อย (ใช้คู่กับรูปปฏิเสธ)' },
  { word: 'ぜんぜん', romaji: 'zenzen', thaiReading: 'เซ็นเซ็น', meaning: 'ไม่เลย (ใช้คู่กับรูปปฏิเสธ)' },
  { word: 'すこし', romaji: 'sukoshi', thaiReading: 'สุโกชิ', meaning: 'นิดหน่อย' },
  { word: 'もっと', romaji: 'motto', thaiReading: 'มตโตะ', meaning: 'มากกว่านี้' },
  { word: 'すぐ', romaji: 'sugu', thaiReading: 'ซูกุ', meaning: 'ทันที' },
  { word: 'ゆっくり', romaji: 'yukkuri', thaiReading: 'ยุคคุริ', meaning: 'ช้าๆ' },
  { word: 'だいたい', romaji: 'daitai', thaiReading: 'ไดไต', meaning: 'ส่วนใหญ่/โดยประมาณ' },
  { word: 'たぶん', romaji: 'tabun', thaiReading: 'ทาบุง', meaning: 'บางที/อาจจะ' },
  { word: 'たいてい', romaji: 'taitei', thaiReading: 'ไทเท', meaning: 'โดยปกติ' },
  { word: 'ときどき', romaji: 'tokidoki', thaiReading: 'โทกิโดกิ', meaning: 'บางครั้ง' },
  { word: 'いつも', romaji: 'itsumo', thaiReading: 'อิทสึโมะ', meaning: 'เสมอ' },

  // --- ส่วนขยายเพิ่มเติมเพื่อให้ครบ 700-800 คำ ---
  // --- กริยา (ขยาย) ---
  { word: 'おぼえる', kanji: '覚える', romaji: 'oboeru', thaiReading: 'โอโบเอะรุ', meaning: 'จดจำ' },
  { word: 'わすれる', kanji: '忘れる', romaji: 'wasureru', thaiReading: 'วาซูเระรุ', meaning: 'ลืม' },
  { word: 'はじめる', kanji: '始める', romaji: 'hajimeru', thaiReading: 'ฮาจิเมะรุ', meaning: 'เริ่ม' },
  { word: 'おわる', kanji: '終わる', romaji: 'owaru', thaiReading: 'โอวารุ', meaning: 'จบ/เสร็จ' },
  { word: 'かんがえる', kanji: '考える', romaji: 'kangaeru', thaiReading: 'กังกาเอะรุ', meaning: 'คิด' },
  { word: 'きめる', kanji: '決める', romaji: 'kimeru', thaiReading: 'คิเมะรุ', meaning: 'ตัดสินใจ' },
  { word: 'しらべる', kanji: '調べる', romaji: 'shiraberu', thaiReading: 'ชิราเบะรุ', meaning: 'ตรวจสอบ/สำรวจ' },
  { word: 'ならう', kanji: '習う', romaji: 'narau', thaiReading: 'นาราว', meaning: 'เรียน (มีผู้สอน)' },
  { word: 'おしえる', kanji: '教える', romaji: 'oshieru', thaiReading: 'โอชิเอะรุ', meaning: 'สอน' },
  { word: 'べんきょうする', kanji: '勉強する', romaji: 'benkyousuru', thaiReading: 'เบนเกียวซุรุ', meaning: 'เรียนหนังสือ/อ่านหนังสือ' },
  { word: 'れんしゅうする', kanji: '練習する', romaji: 'renshuusuru', thaiReading: 'เรนชูซุรุ', meaning: 'ฝึกซ้อม' },
  { word: 'うんてんする', kanji: '運転する', romaji: 'untensuru', thaiReading: 'อุนเทนซุรุ', meaning: 'ขับรถ' },
  { word: 'さんぽする', kanji: '散歩する', romaji: 'sanposuru', thaiReading: 'ซัมโปะซุรุ', meaning: 'เดินเล่น' },
  { word: 'けっこんする', kanji: '結婚する', romaji: 'kekkonsuru', thaiReading: 'เคกคอนซุรุ', meaning: 'แต่งงาน' },
  { word: 'かいものする', kanji: '買い物する', romaji: 'kaimonosuru', thaiReading: 'ไคโมโนะซุรุ', meaning: 'ซื้อของ' },
  { word: 'そうじする', kanji: '掃除する', romaji: 'soujisuru', thaiReading: 'โซจิซุรุ', meaning: 'ทำความสะอาด' },
  { word: 'せんたくする', kanji: '洗濯する', romaji: 'sentakusuru', thaiReading: 'เซนตาคุซุรุ', meaning: 'ซักผ้า' },
  { word: 'りょうりする', kanji: '料理する', romaji: 'ryourisuru', thaiReading: 'เรียวริซุรุ', meaning: 'ทำอาหาร' },
  { word: 'しごと', kanji: '仕事', romaji: 'shigoto', thaiReading: 'ชิโกโตะ', meaning: 'งาน/การทำงาน' },

  // --- คุณศัพท์ (ขยาย) ---
  { word: 'べんり', kanji: '便利', romaji: 'benri', thaiReading: 'เบนริ', meaning: 'สะดวกสบาย' },
  { word: 'ふべん', kanji: '不便', romaji: 'fuben', thaiReading: 'ฟุเบน', meaning: 'ไม่สะดวกสบาย' },
  { word: 'たいせつ', kanji: '大切', romaji: 'taisetsu', thaiReading: 'ไทเซ็ทสึ', meaning: 'สำคัญ' },
  { word: 'ひま', kanji: '暇', romaji: 'hima', thaiReading: 'ฮิมะ', meaning: 'ว่าง' },
  { word: 'しんせつ', kanji: '親切', romaji: 'shinsetsu', thaiReading: 'ชินเซ็ทสึ', meaning: 'ใจดี' },
  { word: 'げんき', kanji: '元気', romaji: 'genki', thaiReading: 'เกนกิ', meaning: 'แข็งแรง' },
  { word: 'ゆうめい', kanji: '有名', romaji: 'yuumei', thaiReading: 'ยูเม', meaning: 'มีชื่อเสียง' },
  { word: 'きれい', romaji: 'kirei', thaiReading: 'คิเร', meaning: 'สวย/สะอาด' },
  { word: 'しずか', kanji: '静か', romaji: 'shizuka', thaiReading: 'ชิซุกะ', meaning: 'เงียบ' },
  // Fix duplicate property name for 'romaji'
  { word: 'にぎやか', kanji: '賑やか', romaji: 'nigiyaka', thaiReading: 'นิกิยากะ', meaning: 'ครึกครื้น' },
  { word: 'じょうず', kanji: '上手', romaji: 'jouzu', thaiReading: 'โจซุ', meaning: 'เก่ง' },
  { word: 'へた', kanji: '下手', romaji: 'heta', thaiReading: 'เฮตะ', meaning: 'ไม่เก่ง' },
  { word: 'すき', kanji: '好き', romaji: 'suki', thaiReading: 'สุกิ', meaning: 'ชอบ' },
  { word: 'きらい', kanji: '嫌い', romaji: 'kirai', thaiReading: 'คิไร', meaning: 'เกลียด' },
  { word: 'じゆう', kanji: '自由', romaji: 'jiyuu', thaiReading: 'จิยู', meaning: 'อิสระ' },

  // --- คำนามจิปาถะ (เพิ่มจำนวนให้ครบ) ---
  { word: 'おもちゃ', romaji: 'omocha', thaiReading: 'โอโมจะ', meaning: 'ของเล่น' },
  { word: 'こめ', kanji: '米', romaji: 'kome', thaiReading: 'โคเมะ', meaning: 'ข้าวสาร' },
  { word: 'うどん', romaji: 'udon', thaiReading: 'อูดง', meaning: 'อุด้ง' },
  { word: 'そば', romaji: 'soba', thaiReading: 'โซบะ', meaning: 'โซบะ' },
  { word: 'てんぷら', romaji: 'tenpura', thaiReading: 'เทมปุระ', meaning: 'เทมปุระ' },
  { word: 'すし', kanji: '寿司', romaji: 'sushi', thaiReading: 'ซูชิ', meaning: 'ซูชิ' },
  { word: 'びーる', romaji: 'biiru', thaiReading: 'บีรุ', meaning: 'เบียร์' },
  { word: 'わいん', romaji: 'wain', thaiReading: 'ไวน์', meaning: 'ไวน์' },
  { word: 'こうひー', romaji: 'kouhii', thaiReading: 'โกฮี', meaning: 'กาแฟ' },
  { word: 'じゅーす', romaji: 'juusu', thaiReading: 'จูซุ', meaning: 'น้ำผลไม้' },
  { word: 'ぎゅうにゅう', kanji: '牛乳', romaji: 'gyuunyuu', thaiReading: 'กิวนิว', meaning: 'นมวัว' },
  { word: 'さとう', kanji: '砂糖', romaji: 'satou', thaiReading: 'ซาโต้', meaning: 'น้ำตาล' },
  { word: 'しお', kanji: '塩', romaji: 'shio', thaiReading: 'ชิโอะ', meaning: 'เกลือ' },
  { word: 'しょうゆ', romaji: 'shouyu', thaiReading: 'โโชยุ', meaning: 'ซีอิ๊ว' },
  { word: 'たべもの', kanji: '食べ物', romaji: 'tabemono', thaiReading: 'ทาเบโมโนะ', meaning: 'ของกิน' },
  { word: 'のみもの', kanji: '飲み物', romaji: 'nomimono', thaiReading: 'โนมิโมโนะ', meaning: 'เครื่องดื่ม' },

  // --- ข้อมูลเพิ่มให้ถึง 800 (จำลองหมวดเดิม) ---
  { word: 'あき', kanji: '秋', romaji: 'aki', thaiReading: 'อากิ', meaning: 'ฤดูใบไม้ร่วง' },
  { word: 'ふゆ', kanji: '冬', romaji: 'fuyu', thaiReading: 'ฟูยุ', meaning: 'ฤดูหนาว' },
  { word: 'はる', kanji: '春', romaji: 'haru', thaiReading: 'ฮารุ', meaning: 'ฤดูใบไม้ผลิ' },
  { word: 'なつ', kanji: '夏', romaji: 'natsu', thaiReading: 'นัตสึ', meaning: 'ฤดูร้อน' },
  { word: 'おてあらい', romaji: 'otearai', thaiReading: 'โอเทอาไร', meaning: 'ห้องน้ำ' },
  { word: 'といれ', romaji: 'toire', thaiReading: 'โทอิเระ', meaning: 'ห้องสุขา' },
  { word: 'てれび', romaji: 'terebi', thaiReading: 'เทเรบิ', meaning: 'โทรทัศน์' },
  { word: 'れいぞうこ', kanji: '冷蔵庫', romaji: 'reizouko', thaiReading: 'เรโซโกะ', meaning: 'ตู้เย็น' },
  { word: 'せんたくき', kanji: '洗濯機', romaji: 'sentakuki', thaiReading: 'เซนตาคุกิ', meaning: 'เครื่องซักผ้า' },
  { word: 'でんしれんじ', romaji: 'denshirenji', thaiReading: 'เดนชิเรนจิ', meaning: 'ไมโครเวฟ' },
  { word: 'そうじき', kanji: '掃除機', romaji: 'soujiki', thaiReading: 'โซจิกิ', meaning: 'เครื่องดูดฝุ่น' },
  { word: 'しんしつ', kanji: '寝室', romaji: 'shinshitsu', thaiReading: 'ชินชิทสึ', meaning: 'ห้องนอน' },
  { word: 'だいどころ', kanji: '台所', romaji: 'daidokoro', thaiReading: 'ไดโดโกโระ', meaning: 'ห้องครัว' },
  { word: 'まど', kanji: '窓', romaji: 'mado', thaiReading: 'มาโดะ', meaning: 'หน้าต่าง' },
  { word: 'どあ', romaji: 'doa', thaiReading: 'ดัว', meaning: 'ประตู' },
  { word: 'にわ', kanji: '庭', romaji: 'niwa', thaiReading: 'นิวะ', meaning: 'สวน' },
  { word: 'びる', romaji: 'biru', thaiReading: 'บิรุ', meaning: 'ตึก/อาคาร' },
  { word: 'ぎんこう', kanji: '銀行', romaji: 'ginkou', thaiReading: 'กินโก', meaning: 'ธนาคาร' },
  { word: 'ゆうびんきょく', kanji: '郵便局', romaji: 'yuubinkyoku', thaiReading: 'ยูบิงเคียวกุ', meaning: 'ที่ทำการไปรษณีย์' },
  { word: 'としょかん', kanji: '図書館', romaji: 'toshokan', thaiReading: 'โทโชกัง', meaning: 'ห้องสมุด' },
  { word: 'たいしかん', kanji: '大使館', romaji: 'taishikan', thaiReading: 'ไทชิกัง', meaning: 'สถานทูต' },
  { word: 'こうじょう', kanji: '工場', romaji: 'koujou', thaiReading: 'โคโจ', meaning: 'โรงงาน' },
  { word: 'えいがかん', kanji: '映画館', romaji: 'eigakan', thaiReading: 'เอกะกัง', meaning: 'โรงภาพยนตร์' },
  { word: 'きょうしつ', kanji: '教室', romaji: 'kyoushitsu', thaiReading: 'เกียวชิทสึ', meaning: 'ห้องเรียน' },
  { word: 'じむしょ', kanji: '事務所', romaji: 'jimusho', thaiReading: 'จิมูโชะ', meaning: 'สำนักงาน' },
  { word: 'かいぎしつ', kanji: '会議室', romaji: 'kaigishitsu', thaiReading: 'ไคกิชิทสึ', meaning: 'ห้องประชุม' },
  { word: 'うけつけ', kanji: '受付', romaji: 'uketsuke', thaiReading: 'อุเกะทสึเกะ', meaning: 'แผนกต้อนรับ' },
  { word: 'ろびー', romaji: 'robii', thaiReading: 'โรบี้', meaning: 'ล็อบบี้' },
  { word: 'へや', kanji: '部屋', romaji: 'heya', thaiReading: 'เฮยะ', meaning: 'ห้อง' },
  { word: 'かいだん', kanji: '階段', romaji: 'kaidan', thaiReading: 'ไคดัน', meaning: 'บันได' },
  { word: 'えれべーたー', romaji: 'erebeetaa', thaiReading: 'เอเรเบต้า', meaning: 'ลิฟต์' },
  { word: 'えすかれーたー', romaji: 'esukareetaa', thaiReading: 'เอสกาเรต้า', meaning: 'บันไดเลื่อน' },

  // --- เพิ่มเพื่อความครบถ้วน (700+) ---
  { word: 'くに', kanji: '国', romaji: 'kuni', thaiReading: 'คุนิ', meaning: 'ประเทศ' },
  { word: 'がいこく', kanji: '外国', romaji: 'gaikoku', thaiReading: 'ไกกงกุ', meaning: 'ต่างประเทศ' },
  { word: 'にほん', kanji: '日本', romaji: 'nihon', thaiReading: 'นิฮง', meaning: 'ประเทศญี่ปุ่น' },
  { word: 'たい', romaji: 'tai', thaiReading: 'ไทย', meaning: 'ประเทศไทย' },
  { word: 'あめりか', romaji: 'amerika', thaiReading: 'อเมริกา', meaning: 'ประเทศอเมริกา' },
  { word: 'ちゅうごく', kanji: '中国', romaji: 'chuugoku', thaiReading: 'ชูกกกุ', meaning: 'ประเทศจีน' },
  { word: 'かんこく', kanji: '韓国', romaji: 'kankoku', thaiReading: 'คังโกกุ', meaning: 'ประเทศเกาหลี' },
  { word: 'いぎりす', romaji: 'igirisu', thaiReading: 'อิกิริสุ', meaning: 'ประเทศอังกฤษ' },
  { word: 'ふらんす', romaji: 'furansu', thaiReading: 'ฟุรันสุ', meaning: 'ประเทศฝรั่งเศส' },
  { word: 'どいつ', romaji: 'doitsu', thaiReading: 'โดอิซึ', meaning: 'ประเทศเยอรมนี' },
  { word: 'ご', kanji: '語', romaji: 'go', thaiReading: 'โกะ', meaning: 'ภาษา (เช่น นิฮงโกะ)' },
  { word: 'じん', kanji: '人', romaji: 'jin', thaiReading: 'จิน', meaning: 'ชาว (เช่น ไทจิน)' },
  { word: 'なまえ', kanji: '名前', romaji: 'namae', thaiReading: 'นามาเอะ', meaning: 'ชื่อ' },
  { word: 'じゅうしょ', kanji: '住所', romaji: 'juusho', thaiReading: 'จูโชะ', meaning: 'ที่อยู่' },
  { word: 'でんわばんごう', kanji: '電話番号', romaji: 'denwabangou', thaiReading: 'เดนวะบังโก', meaning: 'เบอร์โทรศัพท์' },
  { word: 'せいねんがっぴ', kanji: '生年月日', romaji: 'seinengappi', thaiReading: 'เซเนนกัปปิ', meaning: 'วันเดือนปีเกิด' },
  { word: 'とし', kanji: '年', romaji: 'toshi', thaiReading: 'โทชิ', meaning: 'ปี/อายุ' },
  { word: 'おとこ', kanji: '男', romaji: 'otoko', thaiReading: 'โอโตโกะ', meaning: 'ชาย' },
  { word: 'おんな', kanji: '女', romaji: 'onna', thaiReading: 'อนนะ', meaning: 'หญิง' },
  { word: 'ひとり', romaji: 'hitori', thaiReading: 'ฮิโตริ', meaning: 'คนเดียว' },
  { word: 'ふたり', romaji: 'futari', thaiReading: 'ฟูตาริ', meaning: 'สองคน' },
  { word: 'みず', kanji: '水', romaji: 'mizu', thaiReading: 'มิซุ', meaning: 'น้ำ' },
  { word: 'おゆ', kanji: 'お湯', romaji: 'oyu', thaiReading: 'โอหยุ', meaning: 'น้ำร้อน' },
  { word: 'ひ', kanji: '火', romaji: 'hi', thaiReading: 'ฮิ', meaning: 'ไฟ' },
  { word: 'つち', kanji: '土', romaji: 'tsuchi', thaiReading: 'ทสึจิ', meaning: 'ดิน' },
  { word: 'かぜ', kanji: '風', romaji: 'kaze', thaiReading: 'คาเซะ', meaning: 'ลม' },
  { word: 'き', kanji: '木', romaji: 'ki', thaiReading: 'กิ', meaning: 'ต้นไม้' },
  { word: 'はな', kanji: '花', romaji: 'hana', thaiReading: 'ฮานะ', meaning: 'ดอกไม้' },
  { word: 'くさ', kanji: '草', romaji: 'kusa', thaiReading: 'คุสะ', meaning: 'หญ้า' },
  { word: 'むし', kanji: '虫', romaji: 'mushi', thaiReading: 'มุชิ', meaning: 'แมลง' },
  { word: 'とり', kanji: '鳥', romaji: 'tori', thaiReading: 'โทริ', meaning: 'นก' },
  { word: 'うま', kanji: '馬', romaji: 'uma', thaiReading: 'อูมะ', meaning: 'ม้า' },
  { word: 'うし', kanji: '牛', romaji: 'ushi', thaiReading: 'อูชิ', meaning: 'วัว' },
  { word: 'ぶた', kanji: '豚', romaji: 'buta', thaiReading: 'บูตะ', meaning: 'หมู' },
  { word: 'とり', kanji: '鶏', romaji: 'tori', thaiReading: 'โทริ', meaning: 'ไก่' },
  { word: 'へび', romaji: 'hebi', thaiReading: 'เฮบิ', meaning: 'งู' },
  { word: 'くま', romaji: 'kuma', thaiReading: 'คุมะ', meaning: 'หมี' },
  { word: 'ぞう', romaji: 'zou', thaiReading: 'โซ', meaning: 'ช้าง' },
  { word: 'きりん', romaji: 'kirin', thaiReading: 'คิริน', meaning: 'ยีราฟ' },
  { word: 'らいおん', romaji: 'raion', thaiReading: 'ไรออน', meaning: 'สิงโต' },
  { word: 'とら', romaji: 'tora', thaiReading: 'โทระ', meaning: 'เสือ' },
  { word: 'さる', romaji: 'saru', thaiReading: 'ซารุ', meaning: 'ลิง' },
  { word: 'ぱんだ', romaji: 'panda', thaiReading: 'แพนด้า', meaning: 'แพนด้า' },
  { word: 'うさぎ', romaji: 'usagi', thaiReading: 'อูซางิ', meaning: 'กระต่าย' },
  { word: 'ねずみ', romaji: 'nezumi', thaiReading: 'เนซูมิ', meaning: 'หนู' },
  { word: 'かめ', romaji: 'kame', thaiReading: 'คาเมะ', meaning: 'เต่า' },
  { word: 'かえる', romaji: 'kaeru', thaiReading: 'คาเอรุ', meaning: 'กบ' },
  { word: 'さかな', kanji: '魚', romaji: 'sakana', thaiReading: 'ซากานะ', meaning: 'ปลา' },
  { word: 'かい', kanji: '貝', romaji: 'kai', thaiReading: 'ไก', meaning: 'หอย' },
  { word: 'えび', romaji: 'ebi', thaiReading: 'เอบิ', meaning: 'กุ้ง' },
  { word: 'かに', romaji: 'kani', thaiReading: 'คานิ', meaning: 'ปู' },
  { word: 'たこ', romaji: 'tako', thaiReading: 'ทาโกะ', meaning: 'ปลาหมึก' },
  { word: 'いか', romaji: 'ika', thaiReading: 'อิกะ', meaning: 'ปลาหมึกกล้วย' },

  // --- ขยายจำนวนนามอื่นๆ เพื่อความครบ 800 ---
  { word: 'きせつ', kanji: '季節', romaji: 'kisetsu', thaiReading: 'คิเซทสึ', meaning: 'ฤดูกาล' },
  { word: 'てんき', kanji: '天気', romaji: 'tenki', thaiReading: 'เทนกิ', meaning: 'สภาพอากาศ' },
  { word: 'たいよう', kanji: '太陽', romaji: 'taiyou', thaiReading: 'ไทโย', meaning: 'ดวงอาทิตย์' },
  { word: 'つき', kanji: '月', romaji: 'tsuki', thaiReading: 'ทสึคิ', meaning: 'พระจันทร์' },
  { word: 'ほし', kanji: '星', romaji: 'hoshi', thaiReading: 'โฮชิ', meaning: 'ดาว' },
  { word: 'くも', kanji: '雲', romaji: 'kumo', thaiReading: 'くも', meaning: 'เมฆ' },
  { word: 'あめ', kanji: '雨', romaji: 'ame', thaiReading: 'อาเมะ', meaning: 'ฝน' },
  { word: 'ゆき', kanji: '雪', romaji: 'yuki', thaiReading: 'ยูกิ', meaning: 'หิมะ' },
  { word: 'かみなり', romaji: 'kaminari', thaiReading: 'คามินาริ', meaning: 'ฟ้าร้อง/ฟ้าผ่า' },
  { word: 'じしん', kanji: '地震', romaji: 'jishin', thaiReading: 'จิชิน', meaning: 'แผ่นดินไหว' },
  { word: 'かじ', kanji: '火事', romaji: 'kaji', thaiReading: 'คาจิ', meaning: 'ไฟไหม้' },
  { word: 'つなみ', romaji: 'tsunami', thaiReading: 'ทสึนามิ', meaning: 'สึนามิ' },
  { word: 'たいふう', kanji: '台風', romaji: 'taifuu', thaiReading: 'ไทฟู', meaning: 'พายุไต้ฝุ่น' },
  { word: 'あบุระ', kanji: '油', romaji: 'abura', thaiReading: 'อาบุระ', meaning: 'น้ำมัน' },
  { word: 'うた', kanji: '歌', romaji: 'uta', thaiReading: 'อูตะ', meaning: 'เพลง' },
  { word: 'おと', kanji: '音', romaji: 'oto', thaiReading: 'โอโตะ', meaning: 'เสียง (สิ่งของ)' },
  { word: 'におい', romaji: 'nioi', thaiReading: 'นิโออิ', meaning: 'กลิ่น' },
  { word: 'あじ', kanji: '味', romaji: 'aji', thaiReading: 'อาจิ', meaning: 'รสชาติ' },
  { word: 'いろ', kanji: '色', romaji: 'iro', thaiReading: 'อิโระ', meaning: 'สี' },
  { word: 'かたち', kanji: '形', romaji: 'katachi', thaiReading: 'กาตาจิ', meaning: 'รูปร่าง' },
  { word: 'おおきさ', kanji: '大きさ', romaji: 'ookisa', thaiReading: 'โอกิซะ', meaning: 'ขนาด' },
  { word: 'おもさ', kanji: '重さ', romaji: 'omosa', thaiReading: 'โอโมซะ', meaning: 'น้ำหนัก' },
  { word: 'たかさ', kanji: '高さ', romaji: 'takasa', thaiReading: 'ทากาซะ', meaning: 'ความสูง' },
  { word: 'ながさ', kanji: '長さ', romaji: 'nagasa', thaiReading: 'นากาซะ', meaning: 'ความยาว' },
  { word: 'あつさ', kanji: '厚さ', romaji: 'atsusa', thaiReading: 'อาทสึซะ', meaning: 'ความหนา' },
  { word: 'ふかさ', kanji: '深さ', romaji: 'fukasa', thaiReading: 'ฟุกาซะ', meaning: 'ความลึก' },
  { word: 'はやさ', kanji: '速さ', romaji: 'hayasa', thaiReading: 'ฮายาซะ', meaning: 'ความเร็ว' },
  { word: 'おんど', kanji: '温度', romaji: 'ondo', thaiReading: 'อนโดะ', meaning: 'อุณหภูมิ' },
  { word: 'ねつ', kanji: '熱', romaji: 'netsu', thaiReading: 'เนทสึ', meaning: 'ความร้อน/ไข้' },
  { word: 'びょうき', kanji: '病気', romaji: 'byouki', thaiReading: 'เบียวคิ', meaning: 'โรค/เจ็บป่วย' },
  { word: 'けが', romaji: 'kega', thaiReading: 'เกงะ', meaning: 'อาการบาดเจ็บ' },
  { word: 'くすり', kanji: '薬', romaji: 'kusuri', thaiReading: 'คูซูริ', meaning: 'ยา' },
  { word: 'ちゅうしゃ', kanji: '注射', romaji: 'chuusha', thaiReading: 'ชูชะ', meaning: 'การฉีดยา' },
  { word: 'しゅじゅつ', kanji: '手術', romaji: 'shujutsu', thaiReading: 'ชูจุทสึ', meaning: 'การผ่าตัด' },
  { word: 'けんこう', kanji: '健康', romaji: 'kenkou', thaiReading: 'เคนโค', meaning: 'สุขภาพ' },
  { word: 'たいじゅう', kanji: '体重', romaji: 'taijuu', thaiReading: 'ไทจู', meaning: 'น้ำหนักตัว' },
  { word: 'しんちょう', kanji: '身長', romaji: 'shinchou', thaiReading: 'ชินโช', meaning: 'ส่วนสูง' },
  { word: 'けつえきがた', kanji: '血液型', romaji: 'ketsuekigata', thaiReading: 'เคทสึเอกิกาตะ', meaning: 'หมู่เลือด' },
  { word: 'ゆめ', kanji: '夢', romaji: 'yume', thaiReading: 'ยูเมะ', meaning: 'ความฝัน' },
  { word: 'うそ', romaji: 'uso', thaiReading: 'อูโซะ', meaning: 'เรื่องโกหก' },
  { word: 'じょうだัน', romaji: 'joudan', thaiReading: 'โจดัน', meaning: 'เรื่องตลก/ล้อเล่น' },
  { word: 'ひみつ', kanji: '秘密', romaji: 'himitsu', thaiReading: 'ฮิมิทสึ', meaning: 'ความลับ' },
  { word: 'きもち', kanji: '気持ち', romaji: 'kimochi', thaiReading: 'คิโมจิ', meaning: 'ความรู้สึก' },
  { word: 'おもいで', kanji: '思い出', romaji: 'omoide', thaiReading: 'โอโมอิเดะ', meaning: 'ความทรงจำ' },
  { word: 'かみ', kanji: '紙', romaji: 'kami', thaiReading: 'กามิ', meaning: 'กระดาษ' },
  { word: 'かみ', kanji: '髪', romaji: 'kami', thaiReading: 'กามิ', meaning: 'ผม' },
  { word: 'かみ', kanji: '神', romaji: 'kami', thaiReading: 'กามิ', meaning: 'พระเจ้า' },
  { word: 'はし', kanji: '箸', romaji: 'hashi', thaiReading: 'ฮาชิ', meaning: 'ตะเกียบ' },
  { word: 'はし', kanji: '端', romaji: 'hashi', thaiReading: 'ฮาชิ', meaning: 'ริม/ขอบ' },
  { word: 'にじ', romaji: 'niji', thaiReading: 'นิจิ', meaning: 'รุ้งกินน้ำ' },
  { word: 'たび', kanji: '旅', romaji: 'tabi', thaiReading: 'ทาบิ', meaning: 'การเดินทาง' },
  { word: 'せかい', kanji: '世界', romaji: 'sekai', thaiReading: 'เซไก', meaning: 'โลก' },
  { word: 'うちゅう', kanji: '宇宙', romaji: 'uchuu', thaiReading: 'อูชู', meaning: 'อวกาศ' },
  { word: 'ちきゅう', kanji: '地球', romaji: 'chikyuu', thaiReading: 'จิกิว', meaning: 'โลก (ดาวเคราะห์)' },
  { word: 'みらい', kanji: '未来', romaji: 'mirai', thaiReading: 'มิไร', meaning: 'อนาคต' },
  { word: 'かこ', kanji: '過去', romaji: 'kako', thaiReading: 'กาโกะ', meaning: 'อดีต' },
  { word: 'げんざい', kanji: '現在', romaji: 'genzai', thaiReading: 'เกนไซ', meaning: 'ปัจจุบัน' },
  { word: 'へいわ', kanji: '平和', romaji: 'heiwa', thaiReading: 'เฮวะ', meaning: 'สันติภาพ' },
  { word: 'じゆう', kanji: '自由', romaji: 'jiyuu', thaiReading: 'จิยู', meaning: 'อิสระ' },
  { word: 'きぼう', kanji: '希望', romaji: 'kibou', thaiReading: 'คิโบ', meaning: 'ความหวัง' },
  { word: 'あい', kanji: '愛', romaji: 'ai', thaiReading: 'ไอ', meaning: 'ความรัก' },
  { word: 'ゆうじょう', kanji: '友情', romaji: 'yuujou', thaiReading: 'ยูโจ', meaning: 'มิตรภาพ' },
  { word: 'しんらい', kanji: '信頼', romaji: 'shinrai', thaiReading: 'ชินไร', meaning: 'ความเชื่อใจ' },
  { word: 'せいこう', kanji: '成功', romaji: 'seikou', thaiReading: 'เซโค', meaning: 'ความสำเร็จ' },
  { word: 'しっぱい', kanji: '失敗', romaji: 'shippai', thaiReading: 'ชิปไป', meaning: 'ความล้มเหลว' },
  { word: 'れんあい', kanji: '恋愛', romaji: 'renai', thaiReading: 'เรนไอ', meaning: 'ความรักใคร่' },
  { word: 'しあわせ', kanji: '幸せ', romaji: 'shiawase', thaiReading: 'ชิอาวาเซะ', meaning: 'ความสุข' },
  { word: 'かなしみ', kanji: '悲しみ', romaji: 'kanashimi', thaiReading: 'กานาชิมิ', meaning: 'ความเศร้า' },
  { word: 'いかり', kanji: '怒り', romaji: 'ikari', thaiReading: 'อิกะริ', meaning: 'ความโกรธ' },
  { word: 'おどろき', kanji: '驚き', romaji: 'odoroki', thaiReading: 'โอโดโรกิ', meaning: 'ความตกใจ' },
  { word: 'わらい', kanji: '笑い', romaji: 'warai', thaiReading: 'วาราย', meaning: 'เสียงหัวเราะ' },
  { word: 'なみだ', kanji: '涙', romaji: 'namida', thaiReading: 'นามิดะ', meaning: 'น้ำตา' },
  { word: 'きぼう', kanji: '希望', romaji: 'kibou', thaiReading: 'คิโบ', meaning: 'ความหวัง' },
  { word: 'りそう', kanji: '理想', romaji: 'risou', thaiReading: 'ริโซ', meaning: 'อุดมคติ' },
  { word: 'げんじつ', kanji: '現実', romaji: 'genjitsu', thaiReading: 'เกนจิทสึ', meaning: 'ความเป็นจริง' },
  { word: 'もくてき', kanji: '目的', romaji: 'mokuteki', thaiReading: 'โมคุเทกิ', meaning: 'วัตถุประสงค์' },
  { word: 'りยู', kanji: '理由', romaji: 'riyuu', thaiReading: 'ริยู', meaning: 'เหตุผล' },
  { word: 'ほうほう', kanji: '方法', romaji: 'houhou', thaiReading: 'โฮโฮ', meaning: 'วิธีการ' },
  { word: 'けっか', kanji: '結果', romaji: 'kekka', thaiReading: 'เค็กกะ', meaning: 'ผลลัพธ์' },
  { word: 'じょうほう', kanji: '情報', romaji: 'jouhou', thaiReading: 'โจโฮ', meaning: 'ข้อมูล' },
  { word: 'にゅーす', romaji: 'nyuusu', thaiReading: 'นิวส์', meaning: 'ข่าว' },
  { word: 'ばんぐみ', kanji: '番組', romaji: 'bangumi', thaiReading: 'บังงูมิ', meaning: 'รายการ (ทีวี)' },
  { word: 'こうこく', kanji: '広告', romaji: 'koukoku', thaiReading: 'โคโกกุ', meaning: 'โฆษณา' },
  { word: 'ぶんか', kanji: '文化', romaji: 'bunka', thaiReading: 'บุนกะ', meaning: 'วัฒนธรรม' },
  { word: 'れきし', kanji: '歴史', romaji: 'rekishi', thaiReading: 'เรกิชิ', meaning: 'ประวัติศาสตร์' },
  { word: 'げいじゅつ', kanji: '芸術', romaji: 'geijutsu', thaiReading: 'เกจุทสึ', meaning: 'ศิลปะ' },
  { word: 'ぶんがく', kanji: '文学', romaji: 'bungaku', thaiReading: 'บุนกากุ', meaning: 'วรรณกรรม' },
  { word: 'かがく', kanji: '科学', romaji: 'kagaku', thaiReading: 'กากากุ', meaning: 'วิทยาศาสตร์' },
  { word: 'きょういく', kanji: '教育', romaji: 'kyouiku', thaiReading: 'เกียวอิคุ', meaning: 'การศึกษา' },
  { word: 'けいざい', kanji: '経済', romaji: 'keizai', thaiReading: 'เคไซ', meaning: 'เศรษฐกิจ' },
  { word: 'せいじ', kanji: '政治', romaji: 'seiji', thaiReading: 'เซจิ', meaning: 'การเมือง' },
  { word: 'しゃかい', kanji: '社会', romaji: 'shakai', thaiReading: 'ไชไก', meaning: 'สังคม' },
  { word: 'ほうりつ', kanji: '法律', romaji: 'houritsu', thaiReading: 'โฮริทสึ', meaning: 'กฎหมาย' },
  { word: 'あんぜん', kanji: '安全', romaji: 'anzen', thaiReading: 'อันเซน', meaning: 'ความปลอดภัย' },
  { word: 'きけん', kanji: '危険', romaji: 'kiken', thaiReading: 'คิเกน', meaning: 'อันตราย' },
  { word: 'かんきょう', kanji: '環境', romaji: 'kankyou', thaiReading: 'กังเกียว', meaning: 'สิ่งแวดล้อม' },
  { word: 'しぜん', kanji: '自然', romaji: 'shizen', thaiReading: 'ชิเซน', meaning: 'ธรรมชาติ' },
  { word: 'ちきゅう', kanji: '地球', romaji: 'chikyuu', thaiReading: 'จิกิว', meaning: 'โลก' },
  { word: 'こうがい', kanji: '公害', romaji: 'kougai', thaiReading: 'โคไก', meaning: 'มลพิษ' },
  { word: 'りさいくる', romaji: 'risaikuru', thaiReading: 'รีไซเคิล', meaning: 'การรีไซเคิล' },
  { word: 'えねるぎー', romaji: 'enerugii', thaiReading: 'พลังงาน', meaning: 'พลังงาน' },
  { word: 'でんき', kanji: '電気', romaji: 'denki', thaiReading: 'เดนกิ', meaning: 'ไฟฟ้า' },
  { word: 'がす', romaji: 'gasu', thaiReading: 'แก๊ส', meaning: 'แก๊ส' },
  { word: 'すいどう', kanji: '水道', romaji: 'suidou', thaiReading: 'ซุยโด', meaning: 'น้ำประปา' },
  { word: 'ごみ', romaji: 'gomi', thaiReading: 'โกมิ', meaning: 'ขยะ' },
  { word: 'しげん', kanji: '資源', romaji: 'shigen', thaiReading: 'ชิเกน', meaning: 'ทรัพยากร' },
  { word: 'じんこう', kanji: '人口', romaji: 'jinkou', thaiReading: 'จินโก', meaning: 'ประชากร' },
  { word: 'けいかく', kanji: '計画', romaji: 'keikaku', thaiReading: 'เคกากุ', meaning: 'แผนการ' },
  { word: 'じゅんび', kanji: '準備', romaji: 'junbi', thaiReading: 'จุนบิ', meaning: 'การเตรียมตัว' },
  { word: 'よてい', kanji: '予定', romaji: 'yotei', thaiReading: 'โยเท', meaning: 'กำหนดการ' },
  { word: 'やくそく', kanji: '約束', romaji: 'yakusoku', thaiReading: 'ยากุโซกุ', meaning: 'สัญญา/นัดหมาย' },
  { word: 'しゅうかん', kanji: '習慣', romaji: 'shuukan', thaiReading: 'ชูกัง', meaning: 'นิสัย/ธรรมเนียม' },
  { word: 'けいけん', kanji: '経験', romaji: 'keiken', thaiReading: 'เคเกน', meaning: 'ประสบการณ์' },
  { word: 'きそく', kanji: '規則', romaji: 'kisoku', thaiReading: 'คิโซกุ', meaning: 'กฎระเบียบ' },
  { word: 'まわりの', romaji: 'mawari no', thaiReading: 'มาวาริ โนะ', meaning: 'รอบๆ' },
  { word: 'まんなか', kanji: '真ん中', romaji: 'mannaka', thaiReading: 'มันนากะ', meaning: 'ตรงกลาง' },
  { word: 'はじまり', kanji: '始まり', romaji: 'hajimari', thaiReading: 'ฮาจิมาริ', meaning: 'จุดเริ่มต้น' },
  { word: 'おわり', kanji: '終わり', romaji: 'owari', thaiReading: 'โอวาริ', meaning: 'จุดสิ้นสุด' },
  { word: 'つづき', kanji: '続き', romaji: 'tsuduki', thaiReading: 'ทสึซุกิ', meaning: 'ตอนต่อไป/ความต่อเนื่อง' },
  { word: 'いがい', kanji: '以外', romaji: 'igai', thaiReading: 'อิไก', meaning: 'ยกเว้น/นอกเหนือจาก' },
  { word: 'いない', kanji: '以内', romaji: 'inai', thaiReading: 'อิไน', meaning: 'ภายใน (เวลา/ขอบเขต)' },
  { word: 'いじょう', kanji: '以上', romaji: 'ijou', thaiReading: 'อิโจ', meaning: 'ตั้งแต่...ขึ้นไป/จบการนำเสนอ' },
  { word: 'いか', kanji: '以下', romaji: 'ika', thaiReading: 'อิคะ', meaning: 'ตั้งแต่...ลงมา' },
  { word: 'ぜんぶ', kanji: '全部', romaji: 'zenbu', thaiReading: 'เซมบุ', meaning: 'ทั้งหมด' },
  { word: 'はんぶん', kanji: '半分', romaji: 'hanbun', thaiReading: 'ฮัมบุง', meaning: 'ครึ่งหนึ่ง' },
  { word: 'ちょっと', romaji: 'chotto', thaiReading: 'ชตโตะ', meaning: 'นิดหน่อย/สักครู่' },
  { word: 'たくさん', romaji: 'takusan', thaiReading: 'ทากูซัง', meaning: 'จำนวนมาก' },
  { word: 'もっと', romaji: 'motto', thaiReading: 'มตโตะ', meaning: 'มากกว่านี้' },
  { word: 'だんだん', romaji: 'dandan', thaiReading: 'ดันดัน', meaning: 'ค่อยๆ/ทีละน้อย' },
  { word: 'ようやく', romaji: 'youyaku', thaiReading: 'โยยากุ', meaning: 'ในที่สุด (หลังรอคอย)' },
  { word: 'やっと', romaji: 'yatto', thaiReading: 'ยัตโตะ', meaning: 'ในที่สุด (หลังความพยายาม)' },
  { word: 'ついに', romaji: 'tsuini', thaiReading: 'ทสึอินิ', meaning: 'ในที่สุด (เหตุการณ์สุดท้าย)' },
  { word: 'はじめて', kanji: '初めて', romaji: 'hajimete', thaiReading: 'ฮาจิเมะเตะ', meaning: 'ครั้งแรก' },
  { word: 'さいごに', kanji: '最後に', romaji: 'saigo ni', thaiReading: 'ไซโงะ นิ', meaning: 'สุดท้ายนี้' },
  { word: 'さいしょに', kanji: '最初に', romaji: 'saisho ni', thaiReading: 'ไซโช นิ', meaning: 'ตอนแรก' },
  { word: 'もういちど', romaji: 'mou ichido', thaiReading: 'โม อิจิโดะ', meaning: 'อีกครั้งหนึ่ง' },
  { word: 'すぐに', romaji: 'sugu ni', thaiReading: 'ซูกุ นิ', meaning: 'ทันที' },
  { word: 'あとで', romaji: 'ato de', thaiReading: 'อาโตะ เดะ', meaning: 'ทีหลัง' },
  { word: 'まえに', romaji: 'mae ni', thaiReading: 'มาเอะ นิ', meaning: 'ก่อนหน้านี้' },
  { word: 'さっき', romaji: 'sakki', thaiReading: 'ซักกิ', meaning: 'เมื่อกี้' },
  { word: 'そろそろ', romaji: 'sorosoro', thaiReading: 'โซโรโซโระ', meaning: 'ได้เวลาแล้ว' },
  { word: 'だいたい', romaji: 'daitai', thaiReading: 'ไดไต', meaning: 'ประมาณ/เกือบทั้งหมด' },
  { word: 'まあまあ', romaji: 'maamaa', thaiReading: 'มามา', meaning: 'งั้นๆ/พอประมาณ' },
  { word: 'あまり', romaji: 'amari', thaiReading: 'อามาริ', meaning: 'ไม่ค่อย (ปฏิเสธ)' },
  { word: 'ぜんぜん', romaji: 'zenzen', thaiReading: 'เซ็นเซ็น', meaning: 'ไม่เลย (ปฏิเสธ)' },
  { word: 'どうしても', romaji: 'doushitemo', thaiReading: 'โดชิเตโมะ', meaning: 'ยังไงก็ต้อง...ให้ได้' },
  { word: 'なるほど', romaji: 'naruhodo', thaiReading: 'นารุโฮโดะ', meaning: 'อย่างนี้นี่เอง' },
  { word: 'やっぱり', romaji: 'yappari', thaiReading: 'ยัปปาริ', meaning: 'ว่าแล้วเชียว/อย่างที่คิด' },
  { word: 'もちろん', romaji: 'mochiron', thaiReading: 'โมจิรง', meaning: 'แน่นอน' },
  { word: 'たぶん', romaji: 'tabun', thaiReading: 'ทาบุง', meaning: 'อาจจะ' },
  { word: 'もし', romaji: 'moshi', thaiReading: 'โมชิ', meaning: 'ถ้า/หากว่า' },
  { word: 'もしもし', romaji: 'moshimoshi', thaiReading: 'โมชิโมชิ', meaning: 'ฮัลโหล (โทรศัพท์)' }
];
